//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public int Id { get; set; }
        public Nullable<int> AuditoriaPeriodo { get; set; }
        public Nullable<int> AuditoriaCerrado { get; set; }
        public string ServidorCorreo { get; set; }
        public string EmailEmpresa { get; set; }
        public string Version { get; set; }
        public int SucursalEjecucion_Id { get; set; }
    }
}
