//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacionFuncione
    {
        public System.Guid Id { get; set; }
        public string Funcion { get; set; }
        public string Nombre { get; set; }
        public string Comentario { get; set; }
        public string DefincionTecnica { get; set; }
    }
}
