//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriasDetalle
    {
        public System.Guid ID { get; set; }
        public System.Guid Auditoria_Id { get; set; }
        public System.Guid Titulo_Id { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
    }
}
