//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public System.Guid Id { get; set; }
        public string TipoComprobante { get; set; }
        public int NumeroComprobante { get; set; }
        public System.DateTime FechaComprobante { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public int Sucursal_Id { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAlta_Id { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacion_Id { get; set; }
    }
}
