//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public Caja()
        {
            this.OrdenesPagoDetalles = new HashSet<OrdenesPagoDetalle>();
            this.MutualesLiquidacions = new HashSet<MutualesLiquidacion>();
            this.TarjetasLiquidacions = new HashSet<TarjetasLiquidacion>();
        }
    
        public System.Guid Id { get; set; }
        public int SucursalId { get; set; }
        public Nullable<System.Guid> OperadorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FCierre { get; set; }
        public Nullable<float> Inicio { get; set; }
        public Nullable<float> Ingresos { get; set; }
        public Nullable<float> Egresos { get; set; }
        public Nullable<float> Saldo { get; set; }
        public Nullable<float> Cheques { get; set; }
        public Nullable<float> Bonos { get; set; }
        public string PcAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
        public virtual Operador Operadore2 { get; set; }
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
        public virtual Sucursal Sucursale2 { get; set; }
        public virtual ICollection<OrdenesPagoDetalle> OrdenesPagoDetalles { get; set; }
        public virtual ICollection<MutualesLiquidacion> MutualesLiquidacions { get; set; }
        public virtual ICollection<TarjetasLiquidacion> TarjetasLiquidacions { get; set; }
    }
}
