//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesArchivo
    {
        public System.Guid Id { get; set; }
        public System.Guid ClienteId { get; set; }
        public string Descripcion { get; set; }
        public string Path { get; set; }
        public string Archivo { get; set; }
        public Nullable<System.Guid> OperadorId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
