//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public Compra()
        {
            this.ComprasDetalles = new HashSet<ComprasDetalle>();
            this.FacturasCompras = new HashSet<FacturasCompra>();
            this.ProveedoresCuentasCorrientes = new HashSet<ProveedoresCuentasCorriente>();
            this.TitulosConsignacionesVendidas = new HashSet<TitulosConsignacionesVendida>();
            this.RemitosCompras = new HashSet<RemitosCompra>();
        }
    
        public System.Guid Id { get; set; }
        public string LCN { get; set; }
        public LaPaz.Entidades.Enums.TipoComprobanteEnum TipoComprobanteId { get; set; }
        public System.Guid ProveedorId { get; set; }
        public string LetraComprobante { get; set; }
        public int PuntoVenta { get; set; }
        public string NumeroComprobante { get; set; }
        public System.DateTime FechaComprobante { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> ImporteNeto { get; set; }
        public Nullable<decimal> ImporteIVA { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.Guid> BultoId { get; set; }
        public int EstadoCompraId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadoreModificacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursaleModificacion { get; set; }
        public virtual TipoComprobante TiposComprobante { get; set; }
        public virtual ICollection<ComprasDetalle> ComprasDetalles { get; set; }
        public virtual ICollection<FacturasCompra> FacturasCompras { get; set; }
        public virtual ICollection<ProveedoresCuentasCorriente> ProveedoresCuentasCorrientes { get; set; }
        public virtual ICollection<TitulosConsignacionesVendida> TitulosConsignacionesVendidas { get; set; }
        public virtual ICollection<RemitosCompra> RemitosCompras { get; set; }
        public virtual ProveedoresBulto ProveedoresBulto { get; set; }
        public virtual EstadosCompra EstadosCompra { get; set; }
    }
}
