//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    
    public partial class ConsignacionesParaDevolver
    {
        public string Editorial { get; set; }
        public Nullable<System.Guid> TituloId { get; set; }
        public string NombreTitulo { get; set; }
        public string Autor { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> CantidadSinRendir { get; set; }
    }
}
