//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public System.Guid Id { get; set; }
        public string Denominacion { get; set; }
        public string Domicilio { get; set; }
        public string Email { get; set; }
        public Nullable<int> Localidad_Id { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Celular { get; set; }
        public string Comentarios { get; set; }
    }
}
