//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuplicadosTitulosStockAuditado
    {
        public System.Guid TituloId { get; set; }
        public int SucursalId { get; set; }
        public Nullable<int> cant { get; set; }
    }
}
