//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad
    {
        public Especialidad()
        {
            this.Clientes = new HashSet<Cliente>();
            this.TitulosUbicacions = new HashSet<TitulosUbicacion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int ProfesionId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual Profesion Profesiones { get; set; }
        public virtual ICollection<TitulosUbicacion> TitulosUbicacions { get; set; }
    }
}
