//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacione
    {
        public Liquidacione()
        {
            this.LiquidacionPersonals = new HashSet<LiquidacionPersonal>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid LiquidacionId { get; set; }
        public Nullable<float> Importe { get; set; }
        public Nullable<float> Total { get; set; }
        public string Comentario { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual ICollection<LiquidacionPersonal> LiquidacionPersonals { get; set; }
    }
}
