//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteFactura
    {
        public int NroLote { get; set; }
        public int SucursalLote { get; set; }
        public System.Guid OperadorLote { get; set; }
        public string Tipo { get; set; }
        public int PtoVenta { get; set; }
        public int NroDesde { get; set; }
        public int NroHasta { get; set; }
        public Nullable<int> NroActual { get; set; }
        public LaPaz.Entidades.Enums.EstadoLoteEnum Estado { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    }
}
