//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MutualesMovimiento
    {
        public System.Guid ID { get; set; }
        public int MutualId { get; set; }
        public System.Guid CajaMovimientoId { get; set; }
        public decimal Importe { get; set; }
        public Nullable<System.Guid> LiquidacionMutualesId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual CajaMovimiento CajasMovimiento { get; set; }
        public virtual Mutuale Mutuale { get; set; }
        public virtual MutualesLiquidacion MutualesLiquidacion { get; set; }
    }
}
