//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MutualesLiquidacion
    {
        public MutualesLiquidacion()
        {
            this.MutualesMovimientos = new HashSet<MutualesMovimiento>();
        }
    
        public System.Guid Id { get; set; }
        public int MutualId { get; set; }
        public System.Guid CajaId { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public float Importe { get; set; }
        public Nullable<float> Imp2 { get; set; }
        public Nullable<float> Imp3 { get; set; }
        public Nullable<float> Imp4 { get; set; }
        public Nullable<float> Imp5 { get; set; }
        public Nullable<float> Imp6 { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual ICollection<MutualesMovimiento> MutualesMovimientos { get; set; }
    }
}
