//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasDeVenta
    {
        public System.Guid Id { get; set; }
        public System.Guid ComprobanteId { get; set; }
        public string LCN { get; set; }
        public Nullable<System.Guid> ClienteId { get; set; }
        public string NotaVentaTipo { get; set; }
        public string LetraComprobante { get; set; }
        public int PuntoVenta { get; set; }
        public int NumeroComprobante { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FechaNotaVenta { get; set; }
        public Nullable<decimal> ImporteNeto { get; set; }
        public Nullable<decimal> ImporteIva { get; set; }
        public Nullable<int> EstadoVentaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<System.Guid> OperadorAutoriza { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
