//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovedadesOperador
    {
        public int LiquidacionSuc { get; set; }
        public decimal Liquidacion_Id { get; set; }
        public string kcCodOpe { get; set; }
        public Nullable<float> Importe { get; set; }
        public Nullable<float> ImpPag { get; set; }
    }
}
