//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numeradore
    {
        public int Id { get; set; }
        public int SucursalId { get; set; }
        public int TipoNumeradorId { get; set; }
        public string LCN { get; set; }
        public Nullable<int> UltimoNumero { get; set; }
        public Nullable<byte> Copias { get; set; }
        public string ImpresoraPath { get; set; }
        public string ImpresoraPath2 { get; set; }
        public string ImpresoraPuerto { get; set; }
        public string ImpresoraPuerto2 { get; set; }
        public string Lpt1Computadora { get; set; }
        public string Lpt2Computadora { get; set; }
        public string Lpt3Computadora { get; set; }
        public string Lpt4Computadora { get; set; }
        public string PcGr { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    }
}
