//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operador
    {
        public Operador()
        {
            this.ClientesAlta = new HashSet<Cliente>();
            this.ClientesModificacion = new HashSet<Cliente>();
            this.OperadorSucursals = new HashSet<OperadorSucursal>();
            this.ProveedoresAlta = new HashSet<Proveedor>();
            this.ProveedoresModificacion = new HashSet<Proveedor>();
            this.TitulosAlta = new HashSet<Titulo>();
            this.TitulosModificacion = new HashSet<Titulo>();
            this.SubTemas = new HashSet<SubTema>();
            this.SubTemas1 = new HashSet<SubTema>();
            this.Ventas = new HashSet<Venta>();
            this.Ventas1 = new HashSet<Venta>();
            this.Ventas2 = new HashSet<Venta>();
            this.ClientesMontosFavors = new HashSet<ClienteMontoFavor>();
            this.ClientesMontosFavors1 = new HashSet<ClienteMontoFavor>();
            this.TitulosStocks = new HashSet<TituloStock>();
            this.TitulosStocks1 = new HashSet<TituloStock>();
            this.Cajas = new HashSet<Caja>();
            this.Cajas1 = new HashSet<Caja>();
            this.Cajas2 = new HashSet<Caja>();
            this.CajasMovimientos = new HashSet<CajaMovimiento>();
            this.CajasMovimientos1 = new HashSet<CajaMovimiento>();
            this.TarjetasMovimientos = new HashSet<TarjetasMovimiento>();
            this.TarjetasMovimientos1 = new HashSet<TarjetasMovimiento>();
            this.Compras = new HashSet<Compra>();
            this.Compras1 = new HashSet<Compra>();
            this.ComprasDetalles = new HashSet<ComprasDetalle>();
            this.ComprasDetalles1 = new HashSet<ComprasDetalle>();
            this.FacturasCompras = new HashSet<FacturasCompra>();
            this.FacturasCompras1 = new HashSet<FacturasCompra>();
            this.FacturasComprasDetalles = new HashSet<FacturasComprasDetalle>();
            this.FacturasComprasDetalles1 = new HashSet<FacturasComprasDetalle>();
            this.OrdenesPagoComprobantes = new HashSet<OrdenesPagoComprobante>();
            this.OrdenesPagoComprobantes1 = new HashSet<OrdenesPagoComprobante>();
            this.OrdenesPagoDetalles = new HashSet<OrdenesPagoDetalle>();
            this.OrdenesPagoDetalles1 = new HashSet<OrdenesPagoDetalle>();
            this.OrdenPagoCheques = new HashSet<OrdenPagoCheque>();
            this.OrdenPagoCheques1 = new HashSet<OrdenPagoCheque>();
            this.OrdenesPagos = new HashSet<OrdenesPago>();
            this.OrdenesPagos1 = new HashSet<OrdenesPago>();
            this.ProveedoresCuentasCorrientes = new HashSet<ProveedoresCuentasCorriente>();
            this.ProveedoresCuentasCorrientes1 = new HashSet<ProveedoresCuentasCorriente>();
            this.Roles = new HashSet<Role>();
            this.VentasDetalles = new HashSet<VentaDetalle>();
            this.VentasDetalles1 = new HashSet<VentaDetalle>();
            this.VentasReservadas = new HashSet<VentaReservada>();
            this.VentasReservadas1 = new HashSet<VentaReservada>();
            this.TitulosConsignaciones = new HashSet<TitulosConsignacion>();
            this.TitulosConsignaciones1 = new HashSet<TitulosConsignacion>();
            this.TitulosConsignacionesVendidas = new HashSet<TitulosConsignacionesVendida>();
            this.TitulosConsignacionesVendidas1 = new HashSet<TitulosConsignacionesVendida>();
            this.Temas = new HashSet<Tema>();
            this.Temas1 = new HashSet<Tema>();
            this.TiposGastos = new HashSet<TiposGasto>();
            this.TiposGastos1 = new HashSet<TiposGasto>();
            this.Bancos = new HashSet<Banco>();
            this.Bancos1 = new HashSet<Banco>();
            this.Bancos11 = new HashSet<Banco>();
            this.Temas11 = new HashSet<Tema>();
            this.OperadoresFunciones = new HashSet<OperadoresFuncione>();
            this.Autores = new HashSet<Autor>();
            this.Autores1 = new HashSet<Autor>();
            this.ProveedoresSenias2 = new HashSet<ProveedorSenia>();
            this.ProveedoresSenias11 = new HashSet<ProveedorSenia>();
            this.Cuentas = new HashSet<Cuenta>();
            this.Cuentas1 = new HashSet<Cuenta>();
            this.Cuentas2 = new HashSet<Cuenta>();
            this.RemitosCompras = new HashSet<RemitosCompra>();
            this.RemitosCompras1 = new HashSet<RemitosCompra>();
            this.RemitosCompraDetalles = new HashSet<RemitosCompraDetalle>();
            this.RemitosCompraDetalles1 = new HashSet<RemitosCompraDetalle>();
            this.TitulosConsignacionesRendidas = new HashSet<TituloConsignacionRendida>();
            this.TitulosConsignacionesRendidas1 = new HashSet<TituloConsignacionRendida>();
            this.RemitosVentaDetalles = new HashSet<RemitosVentaDetalle>();
            this.RemitosVentaDetalles1 = new HashSet<RemitosVentaDetalle>();
            this.RemitosVentas = new HashSet<RemitosVenta>();
            this.RemitosVentas1 = new HashSet<RemitosVenta>();
            this.ProveedoresPagos = new HashSet<ProveedoresPago>();
            this.ProveedoresPagos1 = new HashSet<ProveedoresPago>();
            this.ProveedoresPagosDetalles = new HashSet<ProveedoresPagosDetalle>();
            this.ProveedoresPagosDetalles1 = new HashSet<ProveedoresPagosDetalle>();
            this.ProveedoresMontosFavorDetalles = new HashSet<ProveedoresMontosFavorDetalle>();
            this.ProveedoresMontosFavorDetalles1 = new HashSet<ProveedoresMontosFavorDetalle>();
            this.ProveedoresMontosFavors = new HashSet<ProveedoresMontosFavor>();
            this.ProveedoresMontosFavors1 = new HashSet<ProveedoresMontosFavor>();
            this.ProveedoresMontosFavors2 = new HashSet<ProveedoresMontosFavor>();
            this.TitulosConsignacionesDevueltas = new HashSet<TitulosConsignacionesDevuelta>();
            this.TitulosMovimiento = new HashSet<TitulosMovimiento>();
            this.TitulosMovimiento1 = new HashSet<TitulosMovimiento>();
        }
    
        public System.Guid Id { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public Nullable<System.DateTime> VigenteDesde { get; set; }
        public Nullable<System.DateTime> VigenteHasta { get; set; }
        public Nullable<System.Guid> PersonalId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual ICollection<Cliente> ClientesAlta { get; set; }
        public virtual ICollection<Cliente> ClientesModificacion { get; set; }
        public virtual ICollection<OperadorSucursal> OperadorSucursals { get; set; }
        public virtual ICollection<Proveedor> ProveedoresAlta { get; set; }
        public virtual ICollection<Proveedor> ProveedoresModificacion { get; set; }
        public virtual ICollection<Titulo> TitulosAlta { get; set; }
        public virtual ICollection<Titulo> TitulosModificacion { get; set; }
        public virtual ICollection<SubTema> SubTemas { get; set; }
        public virtual ICollection<SubTema> SubTemas1 { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
        public virtual ICollection<Venta> Ventas1 { get; set; }
        public virtual ICollection<Venta> Ventas2 { get; set; }
        public virtual ICollection<ClienteMontoFavor> ClientesMontosFavors { get; set; }
        public virtual ICollection<ClienteMontoFavor> ClientesMontosFavors1 { get; set; }
        public virtual ICollection<TituloStock> TitulosStocks { get; set; }
        public virtual ICollection<TituloStock> TitulosStocks1 { get; set; }
        public virtual ICollection<Caja> Cajas { get; set; }
        public virtual ICollection<Caja> Cajas1 { get; set; }
        public virtual ICollection<Caja> Cajas2 { get; set; }
        public virtual ICollection<CajaMovimiento> CajasMovimientos { get; set; }
        public virtual ICollection<CajaMovimiento> CajasMovimientos1 { get; set; }
        public virtual ICollection<TarjetasMovimiento> TarjetasMovimientos { get; set; }
        public virtual ICollection<TarjetasMovimiento> TarjetasMovimientos1 { get; set; }
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual ICollection<Compra> Compras1 { get; set; }
        public virtual ICollection<ComprasDetalle> ComprasDetalles { get; set; }
        public virtual ICollection<ComprasDetalle> ComprasDetalles1 { get; set; }
        public virtual ICollection<FacturasCompra> FacturasCompras { get; set; }
        public virtual ICollection<FacturasCompra> FacturasCompras1 { get; set; }
        public virtual ICollection<FacturasComprasDetalle> FacturasComprasDetalles { get; set; }
        public virtual ICollection<FacturasComprasDetalle> FacturasComprasDetalles1 { get; set; }
        public virtual ICollection<OrdenesPagoComprobante> OrdenesPagoComprobantes { get; set; }
        public virtual ICollection<OrdenesPagoComprobante> OrdenesPagoComprobantes1 { get; set; }
        public virtual ICollection<OrdenesPagoDetalle> OrdenesPagoDetalles { get; set; }
        public virtual ICollection<OrdenesPagoDetalle> OrdenesPagoDetalles1 { get; set; }
        public virtual ICollection<OrdenPagoCheque> OrdenPagoCheques { get; set; }
        public virtual ICollection<OrdenPagoCheque> OrdenPagoCheques1 { get; set; }
        public virtual ICollection<OrdenesPago> OrdenesPagos { get; set; }
        public virtual ICollection<OrdenesPago> OrdenesPagos1 { get; set; }
        public virtual ICollection<ProveedoresCuentasCorriente> ProveedoresCuentasCorrientes { get; set; }
        public virtual ICollection<ProveedoresCuentasCorriente> ProveedoresCuentasCorrientes1 { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<VentaDetalle> VentasDetalles { get; set; }
        public virtual ICollection<VentaDetalle> VentasDetalles1 { get; set; }
        public virtual ICollection<VentaReservada> VentasReservadas { get; set; }
        public virtual ICollection<VentaReservada> VentasReservadas1 { get; set; }
        public virtual ICollection<TitulosConsignacion> TitulosConsignaciones { get; set; }
        public virtual ICollection<TitulosConsignacion> TitulosConsignaciones1 { get; set; }
        public virtual ICollection<TitulosConsignacionesVendida> TitulosConsignacionesVendidas { get; set; }
        public virtual ICollection<TitulosConsignacionesVendida> TitulosConsignacionesVendidas1 { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual ICollection<Tema> Temas { get; set; }
        public virtual ICollection<Tema> Temas1 { get; set; }
        public virtual ICollection<TiposGasto> TiposGastos { get; set; }
        public virtual ICollection<TiposGasto> TiposGastos1 { get; set; }
        public virtual ICollection<Banco> Bancos { get; set; }
        public virtual ICollection<Banco> Bancos1 { get; set; }
        public virtual ICollection<Banco> Bancos11 { get; set; }
        public virtual ICollection<Tema> Temas11 { get; set; }
        public virtual ICollection<OperadoresFuncione> OperadoresFunciones { get; set; }
        public virtual ICollection<Autor> Autores { get; set; }
        public virtual ICollection<Autor> Autores1 { get; set; }
        public virtual ICollection<ProveedorSenia> ProveedoresSenias2 { get; set; }
        public virtual ICollection<ProveedorSenia> ProveedoresSenias11 { get; set; }
        public virtual ICollection<Cuenta> Cuentas { get; set; }
        public virtual ICollection<Cuenta> Cuentas1 { get; set; }
        public virtual ICollection<Cuenta> Cuentas2 { get; set; }
        public virtual ICollection<RemitosCompra> RemitosCompras { get; set; }
        public virtual ICollection<RemitosCompra> RemitosCompras1 { get; set; }
        public virtual ICollection<RemitosCompraDetalle> RemitosCompraDetalles { get; set; }
        public virtual ICollection<RemitosCompraDetalle> RemitosCompraDetalles1 { get; set; }
        public virtual ICollection<TituloConsignacionRendida> TitulosConsignacionesRendidas { get; set; }
        public virtual ICollection<TituloConsignacionRendida> TitulosConsignacionesRendidas1 { get; set; }
        public virtual ICollection<RemitosVentaDetalle> RemitosVentaDetalles { get; set; }
        public virtual ICollection<RemitosVentaDetalle> RemitosVentaDetalles1 { get; set; }
        public virtual ICollection<RemitosVenta> RemitosVentas { get; set; }
        public virtual ICollection<RemitosVenta> RemitosVentas1 { get; set; }
        public virtual ICollection<ProveedoresPago> ProveedoresPagos { get; set; }
        public virtual ICollection<ProveedoresPago> ProveedoresPagos1 { get; set; }
        public virtual ICollection<ProveedoresPagosDetalle> ProveedoresPagosDetalles { get; set; }
        public virtual ICollection<ProveedoresPagosDetalle> ProveedoresPagosDetalles1 { get; set; }
        public virtual ICollection<ProveedoresMontosFavorDetalle> ProveedoresMontosFavorDetalles { get; set; }
        public virtual ICollection<ProveedoresMontosFavorDetalle> ProveedoresMontosFavorDetalles1 { get; set; }
        public virtual ICollection<ProveedoresMontosFavor> ProveedoresMontosFavors { get; set; }
        public virtual ICollection<ProveedoresMontosFavor> ProveedoresMontosFavors1 { get; set; }
        public virtual ICollection<ProveedoresMontosFavor> ProveedoresMontosFavors2 { get; set; }
        public virtual ICollection<TitulosConsignacionesDevuelta> TitulosConsignacionesDevueltas { get; set; }
        public virtual ICollection<TitulosMovimiento> TitulosMovimiento { get; set; }
        public virtual ICollection<TitulosMovimiento> TitulosMovimiento1 { get; set; }
    }
}
