//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesPagoTransferencia
    {
        public int Id { get; set; }
        public System.Guid OrdenPagoId { get; set; }
        public int CuentaId { get; set; }
        public string Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public string BancoDestino { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int SucursalAltaId { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
        public virtual OrdenesPago OrdenesPago { get; set; }
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
    }
}
