//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesPagoComprobante
    {
        public OrdenesPagoComprobante()
        {
            this.OrdenPagoCheques = new HashSet<OrdenPagoCheque>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrdenPagoId { get; set; }
        public System.Guid ProveedorCuentaCorrienteId { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> ImportePagado { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorModificacion { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
        public virtual ICollection<OrdenPagoCheque> OrdenPagoCheques { get; set; }
        public virtual OrdenesPago OrdenesPago { get; set; }
        public virtual ProveedoresCuentasCorriente ProveedoresCuentasCorriente { get; set; }
    }
}
