//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public byte Id { get; set; }
        public Nullable<byte> AudPeriodo { get; set; }
        public Nullable<byte> AudCerrado { get; set; }
        public string MailServer { get; set; }
        public string MailMio { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> FechaCtaCteProveedores { get; set; }
        public Nullable<int> SucursalFisicaId { get; set; }
        public Nullable<System.DateTime> TiempoCaja { get; set; }
        public Nullable<int> SucursalConcentradoraId { get; set; }
        public Nullable<int> SucursalImpresion { get; set; }
    }
}
