//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECIOSACT2
    {
        public System.Guid id { get; set; }
        public Nullable<decimal> PrecioCompraTitulo { get; set; }
        public Nullable<decimal> PrecioVentaTitulo { get; set; }
        public Nullable<float> PrcVta1 { get; set; }
        public Nullable<float> PrcComp { get; set; }
        public Nullable<System.DateTime> FeGr { get; set; }
        public string Cod { get; set; }
    }
}
