//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreVenta
    {
        public System.Guid Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public System.Guid Titulo_Id { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> CantidadAuditada { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public string PC { get; set; }
        public string Operador_Id { get; set; }
    }
}
