//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Titulos = new HashSet<Titulo>();
            this.ProveedoresBancoes = new HashSet<ProveedorBanco>();
            this.Compras = new HashSet<Compra>();
            this.FacturasCompras = new HashSet<FacturasCompra>();
            this.OrdenesPagos = new HashSet<OrdenesPago>();
            this.ProveedoresCuentasCorrientes = new HashSet<ProveedoresCuentasCorriente>();
            this.TitulosConsignaciones = new HashSet<TitulosConsignacion>();
            this.TitulosConsignacionesVendidas = new HashSet<TitulosConsignacionesVendida>();
            this.ProveedoresSenias1 = new HashSet<ProveedorSenia>();
            this.RemitosCompras = new HashSet<RemitosCompra>();
            this.TitulosConsignacionesRendidas = new HashSet<TituloConsignacionRendida>();
            this.ProveedoresPagos = new HashSet<ProveedoresPago>();
            this.ProveedoresMontosFavors = new HashSet<ProveedoresMontosFavor>();
            this.TitulosConsignacionesDevueltas = new HashSet<TitulosConsignacionesDevuelta>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public string Denominacion { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Fax { get; set; }
        public string Contacto { get; set; }
        public string Cuit { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public Nullable<int> CondicionCompraId { get; set; }
        public Nullable<decimal> PorcentajeDescuento { get; set; }
        public string Password { get; set; }
        public Nullable<int> ProveerdorBcoId { get; set; }
        public string CBU { get; set; }
        public Nullable<int> GrupoProveedorId { get; set; }
        public string PaginaWeb { get; set; }
        public string EmailPedido { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Gto { get; set; }
        public int SucursalAltaId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public string PersonaContacto { get; set; }
        public bool Activo { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual CondicionCompra CondicionCompra { get; set; }
        public virtual GruposProveedor GrupoProveedor { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorModificacion { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
        public virtual ICollection<Titulo> Titulos { get; set; }
        public virtual TiposDocumentosIdentidad TiposDocumentosIdentidad { get; set; }
        public virtual ICollection<ProveedorBanco> ProveedoresBancoes { get; set; }
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual ICollection<FacturasCompra> FacturasCompras { get; set; }
        public virtual ICollection<OrdenesPago> OrdenesPagos { get; set; }
        public virtual ICollection<ProveedoresCuentasCorriente> ProveedoresCuentasCorrientes { get; set; }
        public virtual ICollection<TitulosConsignacion> TitulosConsignaciones { get; set; }
        public virtual ICollection<TitulosConsignacionesVendida> TitulosConsignacionesVendidas { get; set; }
        public virtual ICollection<ProveedorSenia> ProveedoresSenias1 { get; set; }
        public virtual ICollection<RemitosCompra> RemitosCompras { get; set; }
        public virtual ICollection<TituloConsignacionRendida> TitulosConsignacionesRendidas { get; set; }
        public virtual ICollection<ProveedoresPago> ProveedoresPagos { get; set; }
        public virtual ICollection<ProveedoresMontosFavor> ProveedoresMontosFavors { get; set; }
        public virtual ICollection<TitulosConsignacionesDevuelta> TitulosConsignacionesDevueltas { get; set; }
    }
}
