//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresMontosFavor
    {
        public ProveedoresMontosFavor()
        {
            this.ProveedoresMontosFavorDetalles = new HashSet<ProveedoresMontosFavorDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CompraId { get; set; }
        public System.Guid ProveedorId { get; set; }
        public Nullable<LaPaz.Entidades.Enums.TipoComprobanteEnum> TipoComprobanteId { get; set; }
        public string LCN { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> ImporteOcupado { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<System.Guid> OperadorAutoriza { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
        public virtual Operador Operadore2 { get; set; }
        public virtual Proveedor Proveedore { get; set; }
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
        public virtual TipoComprobante TiposComprobante { get; set; }
        public virtual ICollection<ProveedoresMontosFavorDetalle> ProveedoresMontosFavorDetalles { get; set; }
    }
}
