//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresPago
    {
        public ProveedoresPago()
        {
            this.ProveedoresPagosDetalles = new HashSet<ProveedoresPagosDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProveedorId { get; set; }
        public LaPaz.Entidades.Enums.TipoComprobanteEnum TipoComprobanteId { get; set; }
        public Nullable<decimal> Senia { get; set; }
        public Nullable<decimal> Recargo { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> ImpFac { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Tarjeta { get; set; }
        public Nullable<decimal> Cheque { get; set; }
        public Nullable<decimal> Transferencia { get; set; }
        public string PcAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public int SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
        public virtual Proveedor Proveedore { get; set; }
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
        public virtual TipoComprobante TiposComprobante { get; set; }
        public virtual ICollection<ProveedoresPagosDetalle> ProveedoresPagosDetalles { get; set; }
    }
}
