//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresBulto
    {
        public ProveedoresBulto()
        {
            this.Compras = new HashSet<Compra>();
            this.FacturasCompras = new HashSet<FacturasCompra>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProveedorId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.Guid> TransporteId { get; set; }
        public Nullable<short> Cantidad { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<float> Peso { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual ICollection<FacturasCompra> FacturasCompras { get; set; }
        public virtual Transporte Transporte { get; set; }
    }
}
