//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public System.Guid Id { get; set; }
        public Nullable<int> SucursalCompId { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> PuntoVenta { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> CobradorId { get; set; }
        public Nullable<System.Guid> OperadorAuId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    }
}
