//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitosCompra
    {
        public RemitosCompra()
        {
            this.RemitosCompraDetalles = new HashSet<RemitosCompraDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CompraId { get; set; }
        public Nullable<int> TipoComprobante { get; set; }
        public Nullable<System.Guid> ProveedorId { get; set; }
        public string LCN { get; set; }
        public Nullable<System.Guid> BultoId { get; set; }
        public int PuntoVenta { get; set; }
        public string NumeroComprobante { get; set; }
        public string Concepto { get; set; }
        public System.DateTime FechaComprobante { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<decimal> ImporteNeto { get; set; }
        public Nullable<decimal> ImporteIVA { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual ICollection<RemitosCompraDetalle> RemitosCompraDetalles { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
        public virtual Proveedor Proveedore { get; set; }
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
        public virtual EstadosCompra EstadosCompra { get; set; }
    }
}
