//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitosVentaDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid RemitoVentaId { get; set; }
        public System.Guid TituloId { get; set; }
        public Nullable<int> CntPr { get; set; }
        public Nullable<int> CntCn { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<decimal> PrecioBase { get; set; }
        public Nullable<int> CntVendida { get; set; }
        public Nullable<int> CntDevuelta { get; set; }
    
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorModificacion { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
        public virtual Titulo Titulo { get; set; }
        public virtual RemitosVenta RemitosVenta { get; set; }
    }
}
