//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitosVenta
    {
        public RemitosVenta()
        {
            this.RemitosVentaDetalles = new HashSet<RemitosVentaDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public string LCN { get; set; }
        public Nullable<System.Guid> VentaId { get; set; }
        public Nullable<int> TipoComprobante { get; set; }
        public Nullable<System.Guid> ClienteId { get; set; }
        public int PuntoVenta { get; set; }
        public string NumeroComprobante { get; set; }
        public string Concepto { get; set; }
        public System.DateTime FechaComprobante { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<decimal> ImporteNeto { get; set; }
        public Nullable<decimal> ImporteIVA { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual Cliente ClienteConsignado { get; set; }
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorModificacion { get; set; }
        public virtual ICollection<RemitosVentaDetalle> RemitosVentaDetalles { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
    }
}
