//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VTAS_CTES
    {
        public int ClienteSuc { get; set; }
        public decimal Cliente_Id { get; set; }
        public string CodTipo { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public System.Guid Libro_Id { get; set; }
        public string Titulo { get; set; }
        public decimal Autor_Id { get; set; }
        public Nullable<int> vp { get; set; }
        public Nullable<int> vc { get; set; }
    }
}
