//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    
    public partial class ReporteConsignacionesVendidasRow
    {
        public Nullable<int> Cantidad { get; set; }
        public string Codigo { get; set; }
        public string NombreTitulo { get; set; }
        public string Proveedor { get; set; }
        public Nullable<decimal> PrecioCompraUnitario { get; set; }
        public Nullable<decimal> PrecioCompraSubtotal { get; set; }
    }
}
