//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    
    public partial class ReporteVentasRow
    {
        public System.Guid TituloId { get; set; }
        public string NombreTitulo { get; set; }
        public string Tema { get; set; }
        public string Editorial { get; set; }
        public string Proveedor { get; set; }
        public string Operador { get; set; }
        public Nullable<int> CantidadPropia { get; set; }
        public Nullable<int> CantidadConsig { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string ISBN { get; set; }
    }
}
