//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    
    public partial class ReporteCajaResumidaComposicion
    {
        public decimal Efectivo { get; set; }
        public decimal Tarjeta { get; set; }
        public decimal Cheque { get; set; }
        public decimal Depositos { get; set; }
        public int Vales { get; set; }
    }
}
