//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolesCtaCte
    {
        public rolesCtaCte()
        {
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
