//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    
    public partial class RptInformeCajaRow
    {
        public string Titulo { get; set; }
        public string NroComprobante { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Concepto { get; set; }
        public string ApellidoYNombre { get; set; }
        public string Operador { get; set; }
        public Nullable<decimal> Senia { get; set; }
        public Nullable<decimal> Recargo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Tipo { get; set; }
        public string FormaPago { get; set; }
        public Nullable<decimal> Factura { get; set; }
    }
}
