//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    
    public partial class RptTarjetasChequesYDepositosRow
    {
        public string Grupo { get; set; }
        public string Nombre { get; set; }
        public string NroComprobante { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaCobro { get; set; }
        public Nullable<decimal> Importe { get; set; }
    }
}
