//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class s00CajasSaldo
    {
        public byte CjLugar { get; set; }
        public string CjOper { get; set; }
        public int CjSuc { get; set; }
        public Nullable<float> fpEfc { get; set; }
        public Nullable<float> fpChq { get; set; }
        public Nullable<float> fpnBono { get; set; }
        public Nullable<float> nCambio { get; set; }
        public Nullable<byte> SucGr { get; set; }
        public string OpeGr { get; set; }
        public Nullable<System.DateTime> FeGr { get; set; }
    }
}
