//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class s00Entidades
    {
        public decimal EntidadTipo { get; set; }
        public decimal Entidad_Id { get; set; }
        public string Cta { get; set; }
        public string cDescrip { get; set; }
        public string Domicilio { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public Nullable<decimal> Provincia_Id { get; set; }
        public Nullable<decimal> Localidad_Id { get; set; }
        public Nullable<float> nMutual { get; set; }
        public Nullable<System.DateTime> FeGr { get; set; }
        public Nullable<byte> SucGr { get; set; }
        public string OpeGr { get; set; }
    }
}
