//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class s00SueNove
    {
        public string kcCodOpe { get; set; }
        public byte nTipo { get; set; }
        public string Concepto { get; set; }
        public Nullable<byte> Cnt { get; set; }
        public Nullable<float> Importe { get; set; }
        public Nullable<float> Tot { get; set; }
        public string Coment { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<byte> RecSuc { get; set; }
        public string RecId { get; set; }
        public string RecLcn { get; set; }
    }
}
