//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class s00SueLiqOpeRec
    {
        public int LiquidacionSuc { get; set; }
        public decimal Liquidacion_Id { get; set; }
        public string kcCodOpe { get; set; }
        public Nullable<float> Tot { get; set; }
        public Nullable<byte> RecSuc { get; set; }
        public string RecId { get; set; }
        public string RecLcn { get; set; }
    }
}
