//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetasMovimiento
    {
        public int Id { get; set; }
        public System.Guid CajaMovimientoId { get; set; }
        public int TarjetaId { get; set; }
        public Nullable<int> BancoId { get; set; }
        public Nullable<System.Guid> TarjetaLiquidacionId { get; set; }
        public string LoteCupon { get; set; }
        public System.DateTime Fecha { get; set; }
        public float Importe { get; set; }
        public Nullable<byte> Estado { get; set; }
        public Nullable<int> NroInt { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Banco Banco { get; set; }
        public virtual CajaMovimiento CajasMovimiento { get; set; }
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
        public virtual TarjetasLiquidacion TarjetasLiquidacion { get; set; }
    }
}
