//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetasLiquidacion
    {
        public TarjetasLiquidacion()
        {
            this.TarjetasMovimientos = new HashSet<TarjetasMovimiento>();
        }
    
        public System.Guid Id { get; set; }
        public int TarjetaId { get; set; }
        public System.Guid CajaId { get; set; }
        public string TrjLiq { get; set; }
        public Nullable<int> Entidad { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public decimal Importe { get; set; }
        public Nullable<decimal> Imp2 { get; set; }
        public Nullable<decimal> Imp3 { get; set; }
        public Nullable<decimal> Imp4 { get; set; }
        public Nullable<decimal> Imp5 { get; set; }
        public Nullable<decimal> Imp6 { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual ICollection<TarjetasMovimiento> TarjetasMovimientos { get; set; }
    }
}
