//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoComprobante
    {
        public TipoComprobante()
        {
            this.Ventas = new HashSet<Venta>();
            this.ClientesMontosFavor = new HashSet<ClienteMontoFavor>();
            this.CajasMovimientos = new HashSet<CajaMovimiento>();
            this.Compras = new HashSet<Compra>();
            this.FacturasCompras = new HashSet<FacturasCompra>();
            this.OrdenesPagos = new HashSet<OrdenesPago>();
            this.ProveedoresPagos = new HashSet<ProveedoresPago>();
            this.ProveedoresMontosFavors = new HashSet<ProveedoresMontosFavor>();
            this.ProveedoresSenias = new HashSet<ProveedorSenia>();
        }
    
        public LaPaz.Entidades.Enums.TipoComprobanteEnum Id { get; set; }
        public string Nombre { get; set; }
        public string Abreviatura { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string Comprobante { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual ICollection<Venta> Ventas { get; set; }
        public virtual ICollection<ClienteMontoFavor> ClientesMontosFavor { get; set; }
        public virtual ICollection<CajaMovimiento> CajasMovimientos { get; set; }
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual ICollection<FacturasCompra> FacturasCompras { get; set; }
        public virtual ICollection<OrdenesPago> OrdenesPagos { get; set; }
        public virtual ICollection<ProveedoresPago> ProveedoresPagos { get; set; }
        public virtual ICollection<ProveedoresMontosFavor> ProveedoresMontosFavors { get; set; }
        public virtual ICollection<ProveedorSenia> ProveedoresSenias { get; set; }
    }
}
