//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titulo
    {
        public Titulo()
        {
            this.TitulosStocks = new HashSet<TituloStock>();
            this.ComprasDetalles = new HashSet<ComprasDetalle>();
            this.FacturasComprasDetalles = new HashSet<FacturasComprasDetalle>();
            this.VentasDetalles = new HashSet<VentaDetalle>();
            this.TitulosConsignaciones = new HashSet<TitulosConsignacion>();
            this.TitulosConsignacionesVendidas = new HashSet<TitulosConsignacionesVendida>();
            this.ClientesMontosFavorDetalles = new HashSet<ClientesMontosFavorDetalle>();
            this.RemitosCompraDetalles = new HashSet<RemitosCompraDetalle>();
            this.TitulosConsignacionesRendidasDetalles = new HashSet<TituloConsignacionRendidasDetalle>();
            this.RemitosVentaDetalles = new HashSet<RemitosVentaDetalle>();
            this.NotasDeVentaDetalles = new HashSet<NotasDeVentaDetalle>();
            this.ProveedoresMontosFavorDetalles = new HashSet<ProveedoresMontosFavorDetalle>();
            this.TitulosConsignacionesDevueltasDetalles = new HashSet<TitulosConsignacionesDevueltasDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public string Cod { get; set; }
        public string ISBN { get; set; }
        public string NombreTitulo { get; set; }
        public Nullable<System.Guid> ProveedorId { get; set; }
        public Nullable<int> AutorId { get; set; }
        public Nullable<int> EditorialId { get; set; }
        public Nullable<int> TemaId { get; set; }
        public Nullable<int> SubtemaId { get; set; }
        public Nullable<decimal> PrecioVentaTitulo { get; set; }
        public Nullable<decimal> PrecioCompraTitulo { get; set; }
        public string CodigoBarra { get; set; }
        public string ISBNg { get; set; }
        public Nullable<System.DateTime> FechaAltaTitulo { get; set; }
        public Nullable<int> TipoArticuloId { get; set; }
        public Nullable<int> ModoStockId { get; set; }
        public Nullable<int> TipoTituloId { get; set; }
        public Nullable<int> UnidadesId { get; set; }
        public Nullable<int> TomosTitulosId { get; set; }
        public Nullable<int> EstadoTituloId { get; set; }
        public Nullable<int> AdicionalId { get; set; }
        public Nullable<int> PesoTitulo { get; set; }
        public Nullable<int> PaisId { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public Nullable<int> PartesId { get; set; }
        public Nullable<int> Paginas { get; set; }
        public Nullable<int> Encuad { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> StkMin { get; set; }
        public Nullable<System.DateTime> FUltVta { get; set; }
        public Nullable<System.DateTime> Fingreso { get; set; }
        public Nullable<int> nControl { get; set; }
        public Nullable<int> UbicacionId { get; set; }
        public Nullable<System.Guid> TituloUnicoId { get; set; }
        public Nullable<int> PresentacionId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<System.Guid> OperadorUltimoPrecioId { get; set; }
        public bool Activo { get; set; }
    
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorModificacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual EstadosTitulo EstadosTitulo { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual SubTema SubTema { get; set; }
        public virtual Tema Tema { get; set; }
        public virtual TiposTitulo TipoArticulo { get; set; }
        public virtual TiposTitulo TipoTitulo { get; set; }
        public virtual TituloPresentacion TituloPresentacion { get; set; }
        public virtual TitulosAdicional TituloAdicional { get; set; }
        public virtual TitulosModoStock TituloModoStock { get; set; }
        public virtual TitulosParte TituloParte { get; set; }
        public virtual TitulosUnico TituloUnico { get; set; }
        public virtual TomosTitulo TomoTitulo { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Unidad Unidad { get; set; }
        public virtual ICollection<TituloStock> TitulosStocks { get; set; }
        public virtual ICollection<ComprasDetalle> ComprasDetalles { get; set; }
        public virtual ICollection<FacturasComprasDetalle> FacturasComprasDetalles { get; set; }
        public virtual ICollection<VentaDetalle> VentasDetalles { get; set; }
        public virtual ICollection<TitulosConsignacion> TitulosConsignaciones { get; set; }
        public virtual ICollection<TitulosConsignacionesVendida> TitulosConsignacionesVendidas { get; set; }
        public virtual Autor Autor { get; set; }
        public virtual ICollection<ClientesMontosFavorDetalle> ClientesMontosFavorDetalles { get; set; }
        public virtual ICollection<RemitosCompraDetalle> RemitosCompraDetalles { get; set; }
        public virtual ICollection<TituloConsignacionRendidasDetalle> TitulosConsignacionesRendidasDetalles { get; set; }
        public virtual ICollection<RemitosVentaDetalle> RemitosVentaDetalles { get; set; }
        public virtual ICollection<NotasDeVentaDetalle> NotasDeVentaDetalles { get; set; }
        public virtual ICollection<ProveedoresMontosFavorDetalle> ProveedoresMontosFavorDetalles { get; set; }
        public virtual ICollection<TitulosConsignacionesDevueltasDetalle> TitulosConsignacionesDevueltasDetalles { get; set; }
    }
}
