//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TituloConsignacionRendidasDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid TituloConsignacionRendidaId { get; set; }
        public System.Guid TituloId { get; set; }
        public decimal PorcentajeDescuento { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public int Cantidad { get; set; }
        public decimal Importe { get; set; }
    
        public virtual Titulo Titulo { get; set; }
        public virtual TituloConsignacionRendida TituloConsignacionRendida { get; set; }
    }
}
