//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitulosUnico
    {
        public TitulosUnico()
        {
            this.Titulos = new HashSet<Titulo>();
        }
    
        public System.Guid Id { get; set; }
        public string ISBN { get; set; }
        public string NombreTitulo { get; set; }
        public Nullable<int> AutorId { get; set; }
        public Nullable<int> EditorialId { get; set; }
        public Nullable<int> TemaId { get; set; }
        public Nullable<int> SubtemaId { get; set; }
        public Nullable<decimal> PrecioVentaTitulo { get; set; }
        public string CodigoBarra { get; set; }
        public Nullable<int> UnidadesId { get; set; }
        public Nullable<int> TomosTitulosId { get; set; }
        public Nullable<int> EstadoTituloId { get; set; }
        public Nullable<int> nAdicional { get; set; }
        public Nullable<int> PesoTitulo { get; set; }
        public Nullable<int> PaisId { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public Nullable<int> nParte { get; set; }
        public string rParte { get; set; }
        public Nullable<int> Paginas { get; set; }
        public Nullable<int> Encuad { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> StkMin { get; set; }
        public Nullable<System.DateTime> FUltVta { get; set; }
        public Nullable<System.DateTime> Fingreso { get; set; }
        public Nullable<int> nControl { get; set; }
        public Nullable<int> PresentacionId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual ICollection<Titulo> Titulos { get; set; }
    }
}
