//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitulosConsignacionesDevueltasDetalle
    {
        public int Id { get; set; }
        public int TituloConsignacionDevueltaId { get; set; }
        public System.Guid TituloId { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Titulo Titulo { get; set; }
        public virtual TitulosConsignacionesDevuelta TitulosConsignacionesDevuelta { get; set; }
    }
}
