//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitulosMovimiento
    {
        public int Id { get; set; }
        public System.Guid TituloId { get; set; }
        public Nullable<LaPaz.Entidades.Enums.TipoComprobanteEnum> TipoComprobanteId { get; set; }
        public Nullable<System.Guid> ComprobanteId { get; set; }
        public Nullable<int> SucursalComprobante { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> CntAntPr { get; set; }
        public Nullable<int> CntAntCn { get; set; }
        public Nullable<int> CntAddPr { get; set; }
        public Nullable<int> CntAddCn { get; set; }
        public int CntMinPr { get; set; }
        public Nullable<int> CntMinCn { get; set; }
        public string PC { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual Operador Operadores { get; set; }
        public virtual Operador Operadores1 { get; set; }
        public virtual Sucursal Sucursales { get; set; }
        public virtual Sucursal Sucursales1 { get; set; }
        public virtual Sucursal Sucursales2 { get; set; }
        public virtual TipoComprobante TiposComprobantes { get; set; }
        public virtual Titulo Titulos { get; set; }
        public virtual Venta Ventas { get; set; }
    }
}
