//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitulosConsignacionesVendida
    {
        public System.Guid Id { get; set; }
        public Nullable<int> nTipo { get; set; }
        public Nullable<System.Guid> ClienteId { get; set; }
        public Nullable<System.Guid> ProveedorId { get; set; }
        public Nullable<System.Guid> TituloId { get; set; }
        public Nullable<System.Guid> ComprobanteId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> CntCn { get; set; }
        public Nullable<float> CntPag { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorModificacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
        public virtual Titulo Titulo { get; set; }
        public virtual TiposConsignacione TiposConsignacione { get; set; }
    }
}
