//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TituloConsignacionRendida
    {
        public TituloConsignacionRendida()
        {
            this.TitulosConsignacionesRendidasDetalles = new HashSet<TituloConsignacionRendidasDetalle>();
            this.ProveedoresPagosDetalles = new HashSet<ProveedoresPagosDetalle>();
            this.ProveedoresPagosDetalles1 = new HashSet<ProveedoresPagosDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public string LCN { get; set; }
        public System.Guid ProveedorId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public decimal Importe { get; set; }
        public string Observaciones { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public int SucursalAltaId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public System.DateTime FechaConsignacion { get; set; }
        public int TipoConsignacionId { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public Nullable<System.DateTime> UltimaFechaPago { get; set; }
    
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorModificacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
        public virtual ICollection<TituloConsignacionRendidasDetalle> TitulosConsignacionesRendidasDetalles { get; set; }
        public virtual ICollection<ProveedoresPagosDetalle> ProveedoresPagosDetalles { get; set; }
        public virtual TiposConsignacione TiposConsignacione { get; set; }
        public virtual ICollection<ProveedoresPagosDetalle> ProveedoresPagosDetalles1 { get; set; }
    }
}
