//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitulosUbicacion
    {
        public int Id { get; set; }
        public Nullable<int> Piso { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> TemaId { get; set; }
        public Nullable<int> EspecialidadId { get; set; }
        public Nullable<int> SubEspecialidadId { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Especialidad Especialidade { get; set; }
    }
}
