//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public int rol { get; set; }
        public System.Guid lapazUser { get; set; }
        public Nullable<int> Sucursal { get; set; }
    }
}
