//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vale
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CajaId { get; set; }
        public Nullable<int> MutualId { get; set; }
        public string NroVale { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<System.Guid> OperadorCajaId { get; set; }
        public Nullable<int> sTipo { get; set; }
        public Nullable<int> sSuc { get; set; }
        public string sId { get; set; }
        public Nullable<System.DateTime> sFecha { get; set; }
        public string sComprob { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<System.Guid> OperadorAutoriza { get; set; }
    
        public virtual Mutuale Mutuale { get; set; }
    }
}
