//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPaz.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.VentasDetalles = new HashSet<VentaDetalle>();
            this.NotasDeVentas = new HashSet<NotasDeVenta>();
        }
    
        public System.Guid Id { get; set; }
        public string LCN { get; set; }
        public LaPaz.Entidades.Enums.TipoComprobanteEnum ComprobanteId { get; set; }
        public System.Guid ClienteId { get; set; }
        public string LetraComprobante { get; set; }
        public int PuntoVenta { get; set; }
        public int NumeroComprobante { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<LaPaz.Entidades.Enums.CondicionVentaEnum> CondicionVentaId { get; set; }
        public string Concepto { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal ImporteIva { get; set; }
        public Nullable<decimal> ImporteSena { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public LaPaz.Entidades.Enums.EstadoVentaEnum EstadoVentaId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<System.Guid> OperadorAutoriza { get; set; }
        public string ValidacionUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CondicionesVenta CondicionesVenta { get; set; }
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorAutorizacion { get; set; }
        public virtual Operador OperadoreModificacion { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
        public virtual TipoComprobante TiposComprobante { get; set; }
        public virtual EstadoVenta EstadosVenta { get; set; }
        public virtual ICollection<VentaDetalle> VentasDetalles { get; set; }
        public virtual ICollection<NotasDeVenta> NotasDeVentas { get; set; }
    }
}
