
INSERT INTO [LCorrientes].dbo.[ClientesMontosFavor]
           ([Id]
           ,[VentaId]
           ,[ClienteId]
           ,[FechaComprobante]
           ,[TipoComprobanteId]
           ,[LCN]
           ,[Concepto]
           ,[Importe]
           ,[ImpOcupado]
           ,[FechaAnulacion]
           ,[OperadorAutoriza]
           ,[Observaciones]
           ,[FechaAlta]
           ,[SucursalAltaId]
           ,[OperadorAltaId]
           ,[FechaModificacion]
           ,[SucursalModificacionId]
           ,[OperadorModificacionId])
     (
SELECT [Id]
      ,[VentaId]
      ,[ClienteId]
      ,[FechaComprobante]
      ,[TipoComprobanteId]
      ,[LCN]
      ,[Concepto]
      ,[Importe]
      ,[ImpOcupado]
      ,[FechaAnulacion]
      ,[OperadorAutoriza]
      ,[Observaciones]
      ,[FechaAlta]
      ,[SucursalAltaId]
      ,[OperadorAltaId]
      ,[FechaModificacion]
      ,[SucursalModificacionId]
      ,[OperadorModificacionId]
  FROM LCorrientesFeria.[dbo].[ClientesMontosFavor]
where FechaAlta > '2017-07-20 14:30'
	 )

