'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Comentarios
    Public Property id As System.Guid
    Public Property comentario As String


    Public Overridable Property ComentariosClientes As ICollection(Of ComentariosClientes) = New HashSet(Of ComentariosClientes)

End Class
