'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ComentariosClientes
    Public Property Cliente As System.Guid
    Public Property Comentario As System.Guid
    Public Property baja As Nullable(Of Boolean)
    Public Property Fecha As Nullable(Of Date)

    Public Overridable Property Comentarios1 As Comentarios
    Public Overridable Property Clientes As Clientes

End Class
