'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class users
    Public Property id As Integer
    Public Property usuario As String
    Public Property password As String
    Public Property rol As Integer
    Public Property lapazUser As System.Guid
    Public Property Sucursal As Nullable(Of Integer)

    Public Overridable Property roles As rolesCtaCte

End Class
