//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TituloMigracion
{
    public System.Guid Id { get; set; }
    public string Cod { get; set; }
    public string ISBN { get; set; }
    public string NombreTitulo { get; set; }
    public Nullable<System.Guid> ProveedorId { get; set; }
    public Nullable<int> AutorId { get; set; }
    public Nullable<int> EditorialId { get; set; }
    public Nullable<int> TemaId { get; set; }
    public Nullable<int> SubtemaId { get; set; }
    public Nullable<decimal> PrecioVentaTitulo { get; set; }
    public Nullable<decimal> PrecioCompraTitulo { get; set; }
    public string CodigoBarra { get; set; }
    public string ISBNg { get; set; }
    public Nullable<System.DateTime> FechaAltaTitulo { get; set; }
    public Nullable<int> TipoArticuloId { get; set; }
    public Nullable<int> ModoStockId { get; set; }
    public Nullable<int> TipoTituloId { get; set; }
    public Nullable<int> UnidadesId { get; set; }
    public Nullable<int> TomosTitulosId { get; set; }
    public Nullable<int> EstadoTituloId { get; set; }
    public Nullable<int> AdicionalId { get; set; }
    public Nullable<int> PesoTitulo { get; set; }
    public Nullable<int> PaisId { get; set; }
    public Nullable<System.DateTime> FechaEdicion { get; set; }
    public Nullable<int> IdiomaId { get; set; }
    public Nullable<int> PartesId { get; set; }
    public Nullable<int> Paginas { get; set; }
    public Nullable<int> Encuad { get; set; }
    public string Comentario { get; set; }
    public Nullable<int> StkMin { get; set; }
    public Nullable<System.DateTime> FUltVta { get; set; }
    public Nullable<System.DateTime> Fingreso { get; set; }
    public Nullable<int> nControl { get; set; }
    public Nullable<int> UbicacionId { get; set; }
    public Nullable<System.Guid> TituloUnicoId { get; set; }
    public Nullable<int> PresentacionId { get; set; }
    public Nullable<System.DateTime> FechaAlta { get; set; }
    public Nullable<int> SucursalAltaId { get; set; }
    public Nullable<System.Guid> OperadorAltaId { get; set; }
    public Nullable<System.DateTime> FechaModificacion { get; set; }
    public Nullable<int> SucursalModificacionId { get; set; }
    public Nullable<System.Guid> OperadorModificacionId { get; set; }
}
