//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TituloStockMigracion
{
    public int Id { get; set; }
    public System.Guid TituloId { get; set; }
    public int SucursalId { get; set; }
    public Nullable<int> StkPr { get; set; }
    public Nullable<int> StkCn { get; set; }
    public Nullable<System.DateTime> FechaAlta { get; set; }
    public Nullable<int> SucursalAltaId { get; set; }
    public Nullable<System.Guid> OperadorAltaId { get; set; }
    public Nullable<System.DateTime> FechaModificacion { get; set; }
    public Nullable<int> SucursalModificacionId { get; set; }
    public Nullable<System.Guid> OperadorModificacionId { get; set; }
}
