CREATE TABLE [dbo].[Clientes] (
    [Id]                     UNIQUEIDENTIFIER CONSTRAINT [DF_Clientes_Id] DEFAULT (newid()) NOT NULL,
    [SucursalId]             INT              NULL,
    [Cuenta]                 INT              NULL,
    [Denominacion]           NVARCHAR (80)    NULL,
    [Domicilio]              NCHAR (100)      NULL,
    [DomicilioDoc]           NCHAR (100)      NULL,
    [Telefono]               NCHAR (40)       NULL,
    [Celular]                NCHAR (15)       NULL,
    [Fax]                    NCHAR (15)       NULL,
    [Cuit]                   NVARCHAR (11)    NULL,
    [Mail]                   NCHAR (40)       NULL,
    [VendedorId]             INT              NULL,
    [ProvinciaId]            INT              NULL,
    [LocalidadId]            INT              NULL,
    [CondicionVentaId]       INT              NULL,
    [FechaNacimiento]        DATETIME         NULL,
    [PagoLocal]              BIT              NULL,
    [ZonaId]                 INT              NULL,
    [TipoDocumentoId]        INT              NULL,
    [CondicionIvaId]         INT              NULL,
    [Contacto]               VARCHAR (50)     NULL,
    [ProfesionId]            INT              NULL,
    [EspecialidadId]         INT              NULL,
    [EstadoClienteId]        INT              NULL,
    [AceptaConsig]           BIT              NULL,
    [Imagen]                 NVARCHAR (100)   NULL,
    [Comentarios]            NTEXT            NULL,
    [Temp]                   BIT              NULL,
    [Recargo]                REAL             NULL,
    [Activo]                 BIT              NULL,
    [FechaAlta]              DATETIME         NULL,
    [OperadorAltaId]         UNIQUEIDENTIFIER NULL,
    [SucursalAltaId]         INT              NULL,
    [FechaModificacion]      DATETIME         NULL,
    [OperadorModificacionId] UNIQUEIDENTIFIER NULL,
    [SucursalModificacionId] INT              NULL,
    [MandarMail] BIT NULL, 
    [Llamar] BIT NULL, 
    CONSTRAINT [PK_s00Clientes_1] PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_Clientes_Sucursales] FOREIGN KEY (SucursalId) REFERENCES [Sucursales]([Id]), 
    CONSTRAINT [FK_Clientes_Vendedores] FOREIGN KEY (VendedorId) REFERENCES [Vendedores]([Id]), 
    CONSTRAINT [FK_Clientes_Provincia] FOREIGN KEY (ProvinciaId) REFERENCES Provincias([Id]), 
    CONSTRAINT [FK_Clientes_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [Localidades]([Id]), 
    CONSTRAINT [FK_Clientes_CondicionVenta] FOREIGN KEY ([CondicionVentaId]) REFERENCES [CondicionesVenta]([Id]), 
    CONSTRAINT [FK_Clientes_Zona] FOREIGN KEY ([ZonaId]) REFERENCES [Zonas]([Id]), 
    CONSTRAINT [FK_Clientes_TipoDocumento] FOREIGN KEY ([TipoDocumentoId]) REFERENCES [TiposDocumentosIdentidad]([Id]), 
    CONSTRAINT [FK_Clientes_CondicionIva] FOREIGN KEY (CondicionIvaId) REFERENCES CondicionesIVA(Id), 
    CONSTRAINT [FK_Clientes_Profesion] FOREIGN KEY (ProfesionId) REFERENCES Profesiones(Id), 
    CONSTRAINT [FK_Clientes_Especialidad] FOREIGN KEY (EspecialidadId) REFERENCES Especialidades(Id), 
    CONSTRAINT [FK_Clientes_EstadoClienteId] FOREIGN KEY (EstadoClienteId) REFERENCES EstadosCliente(Id), 
    CONSTRAINT [FK_Clientes_OperadorAlta] FOREIGN KEY (OperadorAltaId) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_Clientes_SucursalAlta] FOREIGN KEY (SucursalAltaId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_Clientes_OperadorModificacion] FOREIGN KEY (OperadorModificacionId) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_Clientes_SucursalModificacion] FOREIGN KEY (SucursalModificacionId) REFERENCES Sucursales(Id)
);


GO
CREATE NONCLUSTERED INDEX [IX_s00Clientes_1]
    ON [dbo].[Clientes]([Denominacion] ASC);

