CREATE TABLE [dbo].[FacturasCompra] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [CompraId]               UNIQUEIDENTIFIER NULL,
    [TipoComprobante]        INT              NULL,
    [ProveedorId]            UNIQUEIDENTIFIER NULL,
    [LCN]                    NCHAR (13)       NULL,
    [BultoId]                UNIQUEIDENTIFIER NULL,
    [PuntoVenta]             INT              NOT NULL,
    [NumeroComprobante]      CHAR (13)        NULL,
    [Concepto]               NVARCHAR (50)    NULL,
    [FechaComprobante]       DATETIME         NOT NULL,
    [FechaVencimiento]       DATETIME         NULL,
    [ImporteNeto]            MONEY            NULL,
    [ImporteIVA]             MONEY            NULL,
    [Observaciones]          NVARCHAR (100)   NULL,
    [EstadoId]               INT              NULL,
    [FechaAlta]              DATETIME         NULL,
    [SucursalAltaId]         INT              NULL,
    [OperadorAltaId]         UNIQUEIDENTIFIER NULL,
    [FechaModificacion]      DATETIME         NULL,
    [SucursalModificacionId] INT              NULL,
    [OperadorModificacionId] UNIQUEIDENTIFIER NULL, 
    CONSTRAINT [PK_FacturasCompra] PRIMARY KEY (Id), 
    CONSTRAINT [FK_FacturasCompra_Comprad] FOREIGN KEY (CompraId) REFERENCES Compras(Id), 
    CONSTRAINT [FK_FacturasCompra_TipoComprobante] FOREIGN KEY (TipoComprobante) REFERENCES TiposComprobantes(Id), 
    CONSTRAINT [FK_FacturasCompra_Proveedor] FOREIGN KEY (ProveedorId) REFERENCES Proveedores(Id), 
    CONSTRAINT [FK_FacturasCompra_Bulto] FOREIGN KEY (BultoId) REFERENCES ProveedoresBultos(Id), 
    CONSTRAINT [FK_FacturasCompra_SucursalAlta] FOREIGN KEY (SucursalAltaId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_FacturasCompra_OperadorAlta] FOREIGN KEY (OperadorAltaId) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_FacturasCompra_SucursalModificacion] FOREIGN KEY (SucursalModificacionId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_FacturasCompra_OperadorModificacion] FOREIGN KEY (OperadorModificacionId) REFERENCES Operadores(Id)
);

