CREATE TABLE [dbo].[OrdenesPagoDetalle] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [OrdenPagoId]            UNIQUEIDENTIFIER NOT NULL,
    [NumeroLinea]            INT              NULL,
    [FechaPago]              DATETIME         NULL,
    [Descuento]              MONEY            NULL,
    [ImportePagado]          MONEY            NULL,
    [Efectivo]               MONEY            NULL,
    [Cheques]                MONEY            NULL,
    [Deposito]               MONEY            NULL,
    [DepositoEfectivo]       MONEY            NULL,
    [FechaAnulacion]         DATETIME         NULL,
    [SucursalAltaId]         INT              NULL,
    [FechaAlta]              DATETIME         NULL,
    [OperadorAltaId]         UNIQUEIDENTIFIER NULL,
    [FechaModificacion]      DATETIME         NULL,
    [OperadorModificacionId] UNIQUEIDENTIFIER NULL,
    [SucursalModificacionId] INT              NULL,
    [Transferencia] MONEY NULL, 
    [Descripcion] VARCHAR(100) NULL, 
    [CajaId] UNIQUEIDENTIFIER NULL, 
    [OperadorAutorizaId] UNIQUEIDENTIFIER NULL, 
    CONSTRAINT [PK_s00OpPagos] PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_OrdenesPagoDetalle_OrdenesPago] FOREIGN KEY ([OrdenPagoId]) REFERENCES [OrdenesPago]([Id]),
	CONSTRAINT [FK_OrdenesPagoDetalle_SucursalesAlta] FOREIGN KEY ([SucursalAltaId]) REFERENCES [dbo].[Sucursales]([Id]), 
	CONSTRAINT [FK_OrdenesPagoDetalle_SucursalesModificacion] FOREIGN KEY ([SucursalModificacionId]) REFERENCES [dbo].[Sucursales]([Id]), 
	CONSTRAINT [FK_OrdenesPagoDetalle_OperadoresAlta] FOREIGN KEY ([OperadorAltaId]) REFERENCES [dbo].[Operadores]([Id]), 
	CONSTRAINT [FK_OrdenesPagoDetalle_OperadoresModificacion] FOREIGN KEY ([OperadorModificacionId]) REFERENCES [dbo].[Operadores]([Id]),
	CONSTRAINT [FK_OrdenesPagoDetalle_Cajas] FOREIGN KEY ([CajaId]) REFERENCES [dbo].[Cajas]([Id])
);

