CREATE TABLE [dbo].[OrdenesPago] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [SucursalId]             INT              NOT NULL,
    [Fecha]                  DATETIME         NOT NULL,
    [LCN]                    NCHAR (13)       NULL,
    [LetraComprobante]       CHAR (1)         NULL,
    [NumeroComprobante]      NCHAR (13)       NULL,
    [TipoGastoId]            INT              NULL,
    [ProveedorId]            UNIQUEIDENTIFIER NOT NULL,
    [Concepto]               NVARCHAR (50)    NULL,
    [RegistraIVACompra]      BIT              NULL,
    [SucursalGastoId]        INT              NULL,
    [CentroCostoId]          INT              NULL,
    [TipoComprobanteId]      INT              NULL,
    [FechaImputacion]        DATETIME         NULL,
    [SubTotal]               MONEY            NOT NULL,
    [Recargo]                MONEY            NULL,
    [Importe]                MONEY            NOT NULL,
    [ImportePagado]          MONEY            NULL,
    [FechaAnulacion]         DATETIME         NULL,
    [RemitoAnticipadoId]     UNIQUEIDENTIFIER NULL,
    [SucursalAltaId]         INT              NULL,
    [FechaAlta]              DATETIME         NULL,
    [OperadorAltaId]         UNIQUEIDENTIFIER NULL,
    [FechaModificacion]      DATETIME         NULL,
    [OperadorModificacionId] UNIQUEIDENTIFIER NULL,
    [SucursalModificacionId] INT              NULL,
    CONSTRAINT [PK_s00Op] PRIMARY KEY CLUSTERED ([Id] ASC),	
    CONSTRAINT [FK_OrdenesPago_Comprobante] FOREIGN KEY ([TipoComprobanteId]) REFERENCES [dbo].[TiposComprobantes]([Id]),
    CONSTRAINT [FK_OrdenesPago_TiposGastos1] FOREIGN KEY ([TipoGastoId]) REFERENCES [dbo].[TiposGastos]([Id]), 
    CONSTRAINT [FK_OrdenesPago_Sucursales] FOREIGN KEY ([SucursalId]) REFERENCES [dbo].[Sucursales]([Id]), 
	CONSTRAINT [FK_OrdenesPago_Proveedores] FOREIGN KEY ([ProveedorId]) REFERENCES [dbo].[Proveedores]([Id]), 
	CONSTRAINT [FK_OrdenesPago_SucursalesGasto] FOREIGN KEY ([SucursalGastoId]) REFERENCES [dbo].[Sucursales]([Id]),
	CONSTRAINT [FK_OrdenesPago_CentrosCostos] FOREIGN KEY ([CentroCostoId]) REFERENCES [dbo].[CentrosCostos]([Id]),
	CONSTRAINT [FK_OrdenesPago_SucursalesAlta] FOREIGN KEY ([SucursalAltaId]) REFERENCES [dbo].[Sucursales]([Id]), 
	CONSTRAINT [FK_OrdenesPago_SucursalesModificacion] FOREIGN KEY ([SucursalModificacionId]) REFERENCES [dbo].[Sucursales]([Id]), 
	CONSTRAINT [FK_OrdenesPago_OperadoresAlta] FOREIGN KEY ([OperadorAltaId]) REFERENCES [dbo].[Operadores]([Id]), 
	CONSTRAINT [FK_OrdenesPago_OperadoresModificacion] FOREIGN KEY ([OperadorModificacionId]) REFERENCES [dbo].[Operadores]([Id])
);

