CREATE TABLE [dbo].[RemitosVenta] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [LCN]                    VARCHAR (13)     NOT NULL,
    [VentaId]                UNIQUEIDENTIFIER NULL,
    [TipoComprobante]        INT              NULL,
    [ClienteId]              UNIQUEIDENTIFIER NULL,
    [PuntoVenta]             INT              NOT NULL,
    [NumeroComprobante]      CHAR (12)        NULL,
    [Concepto]               NVARCHAR (50)    NULL,
    [FechaComprobante]       DATETIME         NOT NULL,
    [FechaVencimiento]       DATETIME         NULL,
    [FechaEmision]           DATETIME         NULL,
    [ImporteNeto]            MONEY            NULL,
    [ImporteIVA]             MONEY            NULL,
    [Observaciones]          NVARCHAR (100)   NULL,
    [EstadoId]               INT              NULL,
    [FechaAlta]              DATETIME         NULL,
    [SucursalAltaId]         INT              NULL,
    [OperadorAltaId]         UNIQUEIDENTIFIER NULL,
    [FechaModificacion]      DATETIME         NULL,
    [SucursalModificacionId] INT              NULL,
    [OperadorModificacionId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_RemitosVentas] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_RemitosVentas_SucursalAlta] FOREIGN KEY (SucursalAltaId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_RemitosVentas_OperadorAlta] FOREIGN KEY (OperadorAltaId) REFERENCES Operadores(Id), 
	CONSTRAINT [FK_RemitosVentas_SucursalModificacion] FOREIGN KEY (SucursalModificacionId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_RemitosVentas_OperadorModificacion] FOREIGN KEY (OperadorModificacionId) REFERENCES Operadores(Id),
	CONSTRAINT [FK_RemitosVentas_Cliente] FOREIGN KEY (ClienteId) REFERENCES Clientes(Id)
);

