CREATE TABLE [dbo].[TitulosMovimiento] (
    [Id]                     INT              IDENTITY (1, 1) NOT NULL,
    [TituloId]               UNIQUEIDENTIFIER NOT NULL,
    [TipoComprobanteId]      INT              NULL,
    [ComprobanteId]          UNIQUEIDENTIFIER NULL,
    [SucursalComprobante]    INT              NULL,
    [Fecha]                  DATETIME         NULL,
    [CntAntPr]               INT              NULL,
    [CntAntCn]               INT              NULL,
    [CntAddPr]               INT              NULL,
    [CntAddCn]               INT              NULL,
    [CntMinPr]               INT              NOT NULL,
    [CntMinCn]               INT              NULL,
    [PC]                     NVARCHAR (30)    NULL,
    [FechaAlta]              DATETIME         NULL,
    [SucursalAltaId]         INT              NULL,
    [OperadorAltaId]         UNIQUEIDENTIFIER NULL,
    [FechaModificacion]      DATETIME         NULL,
    [SucursalModificacionId] INT              NULL,
    [OperadorModificacionId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_TitulosMovimiento_1] PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_TitulosMovimiento_Titulo] FOREIGN KEY (Tituloid) REFERENCES Titulos(id), 
    CONSTRAINT [FK_TitulosMovimiento_Venta] FOREIGN KEY (ComprobanteId) REFERENCES Ventas(Id), 
    CONSTRAINT [FK_TitulosMovimiento_Sucursal] FOREIGN KEY (SucursalComprobante) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_TitulosMovimiento_SucursalAlta] FOREIGN KEY (SucursalAltaId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_TitulosMovimiento_OperadorAlta] FOREIGN KEY (OperadorAltaId) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_TitulosMovimiento_SucursalModificacion] FOREIGN KEY (SucursalModificacionId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_TitulosMovimiento_OperadorModificacion] FOREIGN KEY (OperadorModificacionId) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_TitulosMovimiento_TipoComprobante] FOREIGN KEY (TipoComprobanteId) REFERENCES TiposComprobantes(Id)
);

