CREATE TABLE [dbo].[TITULOSFALTA3] (
    [Cod]         NVARCHAR (17)  NULL,
    [Titulo]      NVARCHAR (50)  NULL,
    [Autor]       NVARCHAR (30)  NULL,
    [nEditorial]  INT            NULL,
    [rEditorial]  NVARCHAR (40)  NULL,
    [nProv]       INT            NULL,
    [rProv]       NVARCHAR (50)  NULL,
    [nTema]       INT            NULL,
    [rTema]       NVARCHAR (40)  NULL,
    [CodSub]      INT            NULL,
    [PrcVta1]     REAL           NULL,
    [PrcComp]     REAL           NULL,
    [ISBN]        NVARCHAR (15)  NULL,
    [CodBarra]    NVARCHAR (13)  NULL,
    [FAlta]       SMALLDATETIME  NULL,
    [ISBNg]       NVARCHAR (15)  NULL,
    [ModoStock]   INT            NULL,
    [nTipoArt]    INT            NULL,
    [nAdicional]  INT            NULL,
    [dePeso]      TINYINT        NULL,
    [nPaisOrigen] INT            NULL,
    [FEdicion]    SMALLDATETIME  NULL,
    [nEstado]     INT            NULL,
    [Idioma]      INT            NULL,
    [nParte]      INT            NULL,
    [rParte]      NVARCHAR (40)  NULL,
    [Paginas]     INT            NULL,
    [Encuad]      TINYINT        NULL,
    [Comentario]  NVARCHAR (100) NULL,
    [StkMin]      SMALLINT       NULL,
    [FUltVta]     SMALLDATETIME  NULL,
    [FeGr]        SMALLDATETIME  NULL,
    [SucGr]       TINYINT        NULL,
    [OpeGr]       NVARCHAR (10)  NULL,
    [Fingreso]    SMALLDATETIME  NULL,
    [nControl]    TINYINT        NULL,
    [nUbi]        SMALLINT       NULL
);

