'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Alumnos
    Public Property Id As Integer
    Public Property ClienteId As Nullable(Of System.Guid)
    Public Property AlumnoCuit As String
    Public Property ntipoDoc As Integer
    Public Property AlumnoNomyApe As String
    Public Property AlumnoDomicilo As String
    Public Property AlumnoTelefono As String
    Public Property AlumnoColegio As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

End Class
