'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Aplicacion
    Public Property Id As Integer
    Public Property AuditoriaPeriodo As Nullable(Of Integer)
    Public Property AuditoriaCerrado As Nullable(Of Integer)
    Public Property ServidorCorreo As String
    Public Property EmailEmpresa As String
    Public Property Version As String
    Public Property SucursalEjecucion_Id As Integer

End Class
