'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AplicacionFunciones
    Public Property Id As System.Guid
    Public Property Funcion As String
    Public Property Nombre As String
    Public Property Comentario As String
    Public Property DefincionTecnica As String

End Class
