'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditoriasDetalle
    Public Property ID As System.Guid
    Public Property Auditoria_Id As System.Guid
    Public Property Titulo_Id As System.Guid
    Public Property Cantidad As Nullable(Of Integer)
    Public Property PrecioVenta As Nullable(Of Decimal)

End Class
