'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Auditorias
    Public Property Id As System.Guid
    Public Property TipoComprobante As String
    Public Property NumeroComprobante As Integer
    Public Property FechaComprobante As Date
    Public Property Concepto As String
    Public Property FechaAnulacion As Nullable(Of Date)
    Public Property Sucursal_Id As Integer
    Public Property FechaAlta As Date
    Public Property OperadorAlta_Id As System.Guid
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacion_Id As Nullable(Of System.Guid)

End Class
