'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CajasMovimientos
    Public Property Id As System.Guid
    Public Property CajaId As System.Guid
    Public Property TipoMovimientoCajaId As Nullable(Of Integer)
    Public Property TipoComprobante As Nullable(Of Integer)
    Public Property ComprobanteId As Nullable(Of System.Guid)
    Public Property Senia As Nullable(Of Decimal)
    Public Property Recargo As Nullable(Of Decimal)
    Public Property Importe As Nullable(Of Decimal)
    Public Property ImpFac As Nullable(Of Decimal)
    Public Property Efectivo As Nullable(Of Decimal)
    Public Property Tarjeta As Nullable(Of Decimal)
    Public Property Cheque As Nullable(Of Decimal)
    Public Property Bono As Nullable(Of Decimal)
    Public Property fpcBono As String
    Public Property Deposito As Nullable(Of Decimal)
    Public Property CajaIdAnt As String
    Public Property CompIdAnt As String
    Public Property CompLcnAnt As String
    Public Property FacturaReservadas As Nullable(Of Integer)
    Public Property PcAlta As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property MutualesMovimientos As ICollection(Of MutualesMovimientos) = New HashSet(Of MutualesMovimientos)

End Class
