'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cajas
    Public Property Id As System.Guid
    Public Property SucursalId As Integer
    Public Property OperadorId As Nullable(Of System.Guid)
    Public Property Fecha As Date
    Public Property FCierre As Nullable(Of Date)
    Public Property Inicio As Nullable(Of Single)
    Public Property Ingresos As Nullable(Of Single)
    Public Property Egresos As Nullable(Of Single)
    Public Property Saldo As Nullable(Of Single)
    Public Property Cheques As Nullable(Of Single)
    Public Property Bonos As Nullable(Of Single)
    Public Property PcAlta As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property MutualesLiquidacion As ICollection(Of MutualesLiquidacion) = New HashSet(Of MutualesLiquidacion)
    Public Overridable Property TarjetasLiquidacion As ICollection(Of TarjetasLiquidacion) = New HashSet(Of TarjetasLiquidacion)

End Class
