'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ChequesTerceros
    Public Property Id As System.Guid
    Public Property CajaMovimientoId As System.Guid
    Public Property BancoId As Integer
    Public Property NroCheque As String
    Public Property Fecha As Nullable(Of Date)
    Public Property FechaCobro As Nullable(Of Date)
    Public Property Importe As Nullable(Of Single)
    Public Property sTipo As Nullable(Of Integer)
    Public Property sSuc As Nullable(Of Integer)
    Public Property sId As Nullable(Of System.Guid)
    Public Property sFecha As Nullable(Of Date)
    Public Property sComprob As String
    Public Property snSec As Nullable(Of Integer)
    Public Property EstadoChequeId As Nullable(Of Integer)
    Public Property OrdenPagoDetalleId As Nullable(Of System.Guid)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property Bancos As Bancos
    Public Overridable Property OrdenPagoCheques As ICollection(Of OrdenPagoCheques) = New HashSet(Of OrdenPagoCheques)

End Class
