'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientesMontosFavor
    Public Property Id As System.Guid
    Public Property VentaId As Nullable(Of System.Guid)
    Public Property ClienteId As System.Guid
    Public Property FechaComprobante As Date
    Public Property TipoComprobanteId As Integer
    Public Property LCN As String
    Public Property Concepto As String
    Public Property Importe As Nullable(Of Decimal)
    Public Property ImpOcupado As Nullable(Of Decimal)
    Public Property FechaAnulacion As Nullable(Of Date)
    Public Property OperadorAutoriza As Nullable(Of System.Guid)
    Public Property Observaciones As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property ClientesMontosFavorDetalle As ICollection(Of ClientesMontosFavorDetalle) = New HashSet(Of ClientesMontosFavorDetalle)

End Class
