'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clientes
    Public Property Id As System.Guid
    Public Property SucursalId As Nullable(Of Integer)
    Public Property Cuenta As Nullable(Of Integer)
    Public Property Denominacion As String
    Public Property Domicilio As String
    Public Property DomicilioDoc As String
    Public Property Telefono As String
    Public Property Celular As String
    Public Property Fax As String
    Public Property Cuit As String
    Public Property Mail As String
    Public Property VendedorId As Nullable(Of Integer)
    Public Property ProvinciaId As Nullable(Of Integer)
    Public Property LocalidadId As Nullable(Of Integer)
    Public Property CondicionVentaId As Nullable(Of Integer)
    Public Property FechaNacimiento As Nullable(Of Date)
    Public Property PagoLocal As Nullable(Of Boolean)
    Public Property ZonaId As Nullable(Of Integer)
    Public Property TipoDocumentoId As Nullable(Of Integer)
    Public Property CondicionIvaId As Nullable(Of Integer)
    Public Property Contacto As String
    Public Property ProfesionId As Nullable(Of Integer)
    Public Property EspecialidadId As Nullable(Of Integer)
    Public Property EstadoClienteId As Nullable(Of Integer)
    Public Property AceptaConsig As Nullable(Of Boolean)
    Public Property Imagen As String
    Public Property Comentarios As String
    Public Property Temp As Nullable(Of Boolean)
    Public Property Recargo As Nullable(Of Single)
    Public Property Activo As Nullable(Of Boolean)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property MandarMail As Boolean
    Public Property Llamar As Boolean
       

    Public Overridable Property ClientesSuscripciones As ICollection(Of ClientesSuscripciones) = New HashSet(Of ClientesSuscripciones)
    Public Overridable Property NotasDeVenta As ICollection(Of NotasDeVenta) = New HashSet(Of NotasDeVenta)
    Public Overridable Property NotasDeVenta1 As ICollection(Of NotasDeVenta) = New HashSet(Of NotasDeVenta)
    Public Overridable Property Presupuestos As ICollection(Of Presupuestos) = New HashSet(Of Presupuestos)

End Class
