'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientesArchivos
    Public Property Id As System.Guid
    Public Property ClienteId As System.Guid
    Public Property Descripcion As String
    Public Property Path As String
    Public Property Archivo As String
    Public Property OperadorId As Nullable(Of System.Guid)
    Public Property Fecha As Nullable(Of Date)

End Class
