'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientesMontosFavorDetalle
    Public Property Id As System.Guid
    Public Property ClientesMontosFavorId As System.Guid
    Public Property TitulosId As System.Guid
    Public Property CantidadPropia As Nullable(Of Integer)
    Public Property CantidadConsig As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property ClientesMontosFavor As ClientesMontosFavor
    Public Overridable Property Titulos As Titulos

End Class
