'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientesCuentasCorriente
    Public Property Id As System.Guid
    Public Property VentaId As System.Guid
    Public Property ClienteId As Nullable(Of System.Guid)
    Public Property Cuota As Byte
    Public Property Fecha As Nullable(Of Date)
    Public Property FechaVencimiento As Nullable(Of Date)
    Public Property FechaUltimoPago As Nullable(Of Date)
    Public Property Importe As Nullable(Of Single)
    Public Property Pagado As Nullable(Of Single)
    Public Property FechaGeneracion As Nullable(Of Date)
    Public Property Observaciones As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

End Class
