'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cobradores
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Abreviatura As String
    Public Property FechaAlta As Date
    Public Property OperadorAltaId As System.Guid
    Public Property SucursalAltaId As Integer
    Public Property FechaModificacion As Date
    Public Property OperadorModificacionId As System.Guid
    Public Property SucursalModificacionId As Integer

End Class
