'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Compras
    Public Property Id As System.Guid
    Public Property LCN As String
    Public Property TipoComprobanteId As Integer
    Public Property ProveedorId As System.Guid
    Public Property LetraComprobante As String
    Public Property PuntoVenta As Integer
    Public Property NumeroComprobante As String
    Public Property FechaComprobante As Date
    Public Property FechaVencimiento As Nullable(Of Date)
    Public Property Concepto As String
    Public Property ImporteNeto As Nullable(Of Decimal)
    Public Property ImporteIVA As Nullable(Of Decimal)
    Public Property Observaciones As String
    Public Property BultoId As Nullable(Of System.Guid)
    Public Property EstadoCompraId As Integer
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property ComprasDetalle As ICollection(Of ComprasDetalle) = New HashSet(Of ComprasDetalle)

End Class
