'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Conceptos
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Abreviatura As String
    Public Property TipoConcepto As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property PersonalConcepto As ICollection(Of PersonalConcepto) = New HashSet(Of PersonalConcepto)
    Public Overridable Property PersonalNovedades As ICollection(Of PersonalNovedades) = New HashSet(Of PersonalNovedades)

End Class
