'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contactos
    Public Property Id As System.Guid
    Public Property Denominacion As String
    Public Property Domicilio As String
    Public Property Email As String
    Public Property Localidad_Id As Nullable(Of Integer)
    Public Property Tel2 As String
    Public Property Tel3 As String
    Public Property Celular As String
    Public Property Comentarios As String

End Class
