'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CuentasMovimientos
    Public Property Id As Integer
    Public Property CuentaId As Integer
    Public Property TipoMovimientoId As Integer
    Public Property FechaMovimiento As Date
    Public Property EstadoMovimientoCuentaId As Nullable(Of Integer)
    Public Property MotivoEstado As String
    Public Property TipoComprobanteId As Nullable(Of Integer)
    Public Property ComprobanteId As Nullable(Of System.Guid)
    Public Property MonedaId As Integer
    Public Property CondicionVentaId As Nullable(Of Integer)
    Public Property NroMovimiento As String
    Public Property FechaCobro As Nullable(Of Date)
    Public Property Descripcion As String
    Public Property Debito As Nullable(Of Decimal)
    Public Property Credito As Nullable(Of Decimal)
    Public Property ResumenConciliacion As String
    Public Property FechaConciliacion As Nullable(Of Date)
    Public Property TipoCarga As Nullable(Of Integer)
    Public Property CajaId As Nullable(Of System.Guid)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property Cuentas As Cuentas

End Class
