'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cuentas
    Public Property Id As Integer
    Public Property TipoCuentaId As Integer
    Public Property Nombre As String
    Public Property Descripcion As String
    Public Property BancoPropioId As Nullable(Of Integer)
    Public Property OperadorId As Nullable(Of System.Guid)
    Public Property Titular As String
    Public Property FechaApertura As Date
    Public Property FechaCierre As Nullable(Of Date)
    Public Property EstadoId As Integer
    Public Property Debitos As Nullable(Of Decimal)
    Public Property Creditos As Nullable(Of Decimal)
    Public Property DebitosConciliado As Nullable(Of Decimal)
    Public Property CreditosConciliado As Nullable(Of Decimal)
    Public Property SucursalAltaId As Integer
    Public Property FechaAlta As Date
    Public Property OperadorAltaId As System.Guid
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property BancosPropios As BancosPropios
    Public Overridable Property TiposCuenta As TiposCuenta
    Public Overridable Property CuentasMovimientos As ICollection(Of CuentasMovimientos) = New HashSet(Of CuentasMovimientos)

End Class
