'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DuplicadosTitulosStock
    Public Property TituloId As System.Guid
    Public Property SucursalId As Integer
    Public Property cant As Nullable(Of Integer)

End Class
