'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FacturasComprasDetalle
    Public Property Id As System.Guid
    Public Property FacturaCompraId As System.Guid
    Public Property TituloId As System.Guid
    Public Property CntPr As Nullable(Of Integer)
    Public Property CntCn As Nullable(Of Integer)
    Public Property PrecioCompra As Nullable(Of Decimal)
    Public Property PrecioVenta As Nullable(Of Decimal)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

End Class
