'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Funciones
    Public Property Id As Integer
    Public Property Descripcion As String
    Public Property kccodfunc As String
    Public Property Comentario As String
    Public Property DefinicionTecnica As String
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property OperadoresFunciones As ICollection(Of OperadoresFunciones) = New HashSet(Of OperadoresFunciones)

End Class
