'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LiquidacionPersonal
    Public Property Id As System.Guid
    Public Property LiquidacionMesAnio As String
    Public Property TipoLiquidacion As Nullable(Of Byte)
    Public Property Importe As Single
    Public Property Fecha As Date
    Public Property ImportePagado As Nullable(Of Single)
    Public Property LiquidacionId As Nullable(Of System.Guid)
    Public Property PersonalId As System.Guid
    Public Property FechaAlta As Date
    Public Property OperadorAltaId As System.Guid
    Public Property FechaModificacion As String
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property Liquidaciones As Liquidaciones
    Public Overridable Property Personal As Personal

End Class
