'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LoteFactura
    Public Property NroLote As Integer
    Public Property SucursalLote As Integer
    Public Property OperadorLote As System.Guid
    Public Property Tipo As String
    Public Property PtoVenta As Integer
    Public Property NroDesde As Integer
    Public Property NroHasta As Integer
    Public Property NroActual As Nullable(Of Integer)
    Public Property Estado As Integer
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

End Class
