'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MovimientosFondoDetalle
    Public Property Id As System.Guid
    Public Property MovimientosFondoId As System.Guid
    Public Property TipoMovimientoFondoId As Nullable(Of Integer)
    Public Property NumeroComprobante As String
    Public Property DescripcionMovimiento As String
    Public Property ImporteDetalle As Nullable(Of Decimal)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

End Class
