'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MovimientosFondo
    Public Property Id As System.Guid
    Public Property SucursalId As Nullable(Of Integer)
    Public Property FechaMovimiento As Nullable(Of Date)
    Public Property TipoMovimientoFondoId As Nullable(Of Integer)
    Public Property TipoComprobanteId As Nullable(Of Integer)
    Public Property LetraComprobante As String
    Public Property NumeroComprobante As String
    Public Property FechaComprobante As Nullable(Of Date)
    Public Property Concepto As String
    Public Property UsCajaOrigenId As Nullable(Of System.Guid)
    Public Property CuentaOrigenId As Nullable(Of Integer)
    Public Property UsCajaDestinoId As Nullable(Of System.Guid)
    Public Property CuentaDestinoId As Nullable(Of Integer)
    Public Property DescripcionMovimiento As String
    Public Property ImporteMovimiento As Nullable(Of Decimal)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

End Class
