'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MutualesMovimientos
    Public Property ID As System.Guid
    Public Property MutualId As Integer
    Public Property CajaMovimientoId As System.Guid
    Public Property Importe As Decimal
    Public Property LiquidacionMutualesId As Nullable(Of System.Guid)
    Public Property Fecha As Nullable(Of Date)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property CajasMovimientos As CajasMovimientos
    Public Overridable Property Mutuales As Mutuales
    Public Overridable Property MutualesLiquidacion As MutualesLiquidacion

End Class
