'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MutualesLiquidacion
    Public Property Id As System.Guid
    Public Property MutualId As Integer
    Public Property CajaId As System.Guid
    Public Property FechaEmision As Date
    Public Property Importe As Single
    Public Property Imp2 As Nullable(Of Single)
    Public Property Imp3 As Nullable(Of Single)
    Public Property Imp4 As Nullable(Of Single)
    Public Property Imp5 As Nullable(Of Single)
    Public Property Imp6 As Nullable(Of Single)
    Public Property FechaAlta As Date
    Public Property OperadorAltaId As System.Guid
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property Cajas As Cajas
    Public Overridable Property MutualesMovimientos As ICollection(Of MutualesMovimientos) = New HashSet(Of MutualesMovimientos)

End Class
