'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NotasDeVenta
    Public Property Id As System.Guid
    Public Property ComprobanteId As System.Guid
    Public Property LCN As String
    Public Property ClienteId As Nullable(Of System.Guid)
    Public Property NotaVentaTipo As String
    Public Property LetraComprobante As String
    Public Property PuntoVenta As Integer
    Public Property NumeroComprobante As Integer
    Public Property Concepto As String
    Public Property FechaNotaVenta As Nullable(Of Date)
    Public Property ImporteNeto As Nullable(Of Decimal)
    Public Property ImporteIva As Nullable(Of Decimal)
    Public Property EstadoVentaId As Nullable(Of Integer)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property OperadorAutoriza As Nullable(Of System.Guid)

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Clientes1 As Clientes
    Public Overridable Property Ventas As Ventas

End Class
