'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NovedadesOperador
    Public Property LiquidacionSuc As Integer
    Public Property Liquidacion_Id As Decimal
    Public Property kcCodOpe As String
    Public Property Importe As Nullable(Of Single)
    Public Property ImpPag As Nullable(Of Single)

End Class
