'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Operadores
    Public Property Id As System.Guid
    Public Property Usuario As String
    Public Property Clave As String
    Public Property VigenteDesde As Nullable(Of Date)
    Public Property VigenteHasta As Nullable(Of Date)
    Public Property PersonalId As Nullable(Of System.Guid)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property OperadoresFunciones As ICollection(Of OperadoresFunciones) = New HashSet(Of OperadoresFunciones)
    Public Overridable Property OperadorSucursal As ICollection(Of OperadorSucursal) = New HashSet(Of OperadorSucursal)
    Public Overridable Property TitulosConsignaciones As ICollection(Of TitulosConsignaciones) = New HashSet(Of TitulosConsignaciones)
    Public Overridable Property TitulosConsignacionesVendidas As ICollection(Of TitulosConsignacionesVendidas) = New HashSet(Of TitulosConsignacionesVendidas)

End Class
