'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrdenesPago
    Public Property Id As System.Guid
    Public Property SucursalId As Integer
    Public Property Fecha As Date
    Public Property LCN As String
    Public Property LetraComprobante As String
    Public Property NumeroComprobante As String
    Public Property TipoGastoId As Nullable(Of Integer)
    Public Property ProveedorId As System.Guid
    Public Property Concepto As String
    Public Property RegistraIVACompra As Nullable(Of Boolean)
    Public Property SucursalGastoId As Nullable(Of Integer)
    Public Property CentroCostoId As Nullable(Of Integer)
    Public Property TipoComprobanteId As Nullable(Of Integer)
    Public Property FechaImputacion As Nullable(Of Date)
    Public Property SubTotal As Decimal
    Public Property Recargo As Nullable(Of Decimal)
    Public Property Importe As Decimal
    Public Property ImportePagado As Nullable(Of Decimal)
    Public Property FechaAnulacion As Nullable(Of Date)
    Public Property RemitoAnticipadoId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property TiposComprobantes As TiposComprobantes
    Public Overridable Property TiposGastos As TiposGastos

End Class
