'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrdenesPagoDetalle
    Public Property Id As System.Guid
    Public Property OrdenPagoId As System.Guid
    Public Property NumeroLinea As Nullable(Of Integer)
    Public Property FechaPago As Nullable(Of Date)
    Public Property Descuento As Nullable(Of Decimal)
    Public Property ImportePagado As Nullable(Of Decimal)
    Public Property Efectivo As Nullable(Of Decimal)
    Public Property Cheques As Nullable(Of Decimal)
    Public Property Deposito As Nullable(Of Decimal)
    Public Property DepositoEfectivo As Nullable(Of Decimal)
    Public Property FechaAnulacion As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

End Class
