'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrdenesPagoComprobantes
    Public Property Id As System.Guid
    Public Property OrdenPagoId As System.Guid
    Public Property ProveedorCuentaCorrienteId As System.Guid
    Public Property Importe As Nullable(Of Decimal)
    Public Property ImportePagado As Nullable(Of Decimal)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property OrdenPagoCheques As ICollection(Of OrdenPagoCheques) = New HashSet(Of OrdenPagoCheques)

End Class
