'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Parametros
    Public Property Id As Byte
    Public Property AudPeriodo As Nullable(Of Byte)
    Public Property AudCerrado As Nullable(Of Byte)
    Public Property MailServer As String
    Public Property MailMio As String
    Public Property Version As Nullable(Of Integer)
    Public Property FechaCtaCteProveedores As Nullable(Of Date)
    Public Property SucursalFisicaId As Nullable(Of Integer)
    Public Property TiempoCaja As Nullable(Of Date)
    Public Property SucursalConcentradoraId As Nullable(Of Integer)
    Public Property SucursalImpresion As Nullable(Of Integer)

End Class
