'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pedidos
    Public Property Id As System.Guid
    Public Property SucursalId As Integer
    Public Property ClienteId As System.Guid
    Public Property TituloId As System.Guid
    Public Property Cantidad As Integer
    Public Property PrioridadesId As Nullable(Of Integer)
    Public Property EstadoPedido As Nullable(Of Integer)
    Public Property FechaPedido As Nullable(Of Date)
    Public Property FechaPedidoProveedor As Nullable(Of Date)
    Public Property OperadorId As Nullable(Of System.Guid)
    Public Property FechaAviso As Nullable(Of Date)
    Public Property FechaVenta As Nullable(Of Date)
    Public Property VentaDetalleId As Nullable(Of System.Guid)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property PedidosDetalle As ICollection(Of PedidosDetalle) = New HashSet(Of PedidosDetalle)

End Class
