'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonalConcepto
    Public Property ID As System.Guid
    Public Property PersonalId As System.Guid
    Public Property ConceptoId As Integer
    Public Property Importe As String
    Public Property Vigente As Nullable(Of Boolean)
    Public Property FechaAlta As Date
    Public Property OperadorAltaId As System.Guid
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property Conceptos As Conceptos
    Public Overridable Property Personal As Personal

End Class
