'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Personal
    Public Property Id As System.Guid
    Public Property ContactoId As Nullable(Of System.Guid)
    Public Property Nombre As String
    Public Property Cuit As String
    Public Property Domicilio As String
    Public Property ProvinciaId As Nullable(Of Integer)
    Public Property LocalidadId As Nullable(Of Integer)
    Public Property CategoriaId As Nullable(Of Integer)
    Public Property SucursalId As Nullable(Of Integer)
    Public Property TipoLiquidacionId As Nullable(Of Integer)
    Public Property Telefono As String
    Public Property Celular As String
    Public Property Fax As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property HoraDesdeM As String
    Public Property HoraHastaM As String
    Public Property HoraDesdeT As String
    Public Property HoraHastaT As String
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property CategoriasOperadores As CategoriasOperadores
    Public Overridable Property LiquidacionPersonal As ICollection(Of LiquidacionPersonal) = New HashSet(Of LiquidacionPersonal)
    Public Overridable Property PersonalConcepto As ICollection(Of PersonalConcepto) = New HashSet(Of PersonalConcepto)
    Public Overridable Property PersonalNovedades As ICollection(Of PersonalNovedades) = New HashSet(Of PersonalNovedades)

End Class
