'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRECIOSACT2
    Public Property id As System.Guid
    Public Property PrecioCompraTitulo As Nullable(Of Decimal)
    Public Property PrecioVentaTitulo As Nullable(Of Decimal)
    Public Property PrcVta1 As Nullable(Of Single)
    Public Property PrcComp As Nullable(Of Single)
    Public Property FeGr As Nullable(Of Date)
    Public Property Cod As String

End Class
