'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Presupuestos
    Public Property Id As System.Guid
    Public Property Fecha As Nullable(Of Date)
    Public Property Concepto As String
    Public Property LCN As String
    Public Property ClienteId As Nullable(Of System.Guid)
    Public Property Descuento As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property VentaId As Nullable(Of System.Guid)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property Clientes As Clientes
    Public Overridable Property PresupuestosDetalle As ICollection(Of PresupuestosDetalle) = New HashSet(Of PresupuestosDetalle)

End Class
