'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PresupuestosDetalle
    Public Property Id As System.Guid
    Public Property PresupuestoId As System.Guid
    Public Property TituloId As System.Guid
    Public Property Cantidad As Nullable(Of Integer)
    Public Property Precio As Nullable(Of Decimal)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property Presupuestos As Presupuestos

End Class
