'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PreVentas
    Public Property Id As System.Guid
    Public Property Cliente_Id As System.Guid
    Public Property Titulo_Id As System.Guid
    Public Property Cantidad As Nullable(Of Integer)
    Public Property CantidadAuditada As Nullable(Of Integer)
    Public Property Precio As Nullable(Of Decimal)
    Public Property FechaGeneracion As Nullable(Of Date)
    Public Property PC As String
    Public Property Operador_Id As String

End Class
