'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProveedoresBultos
    Public Property Id As System.Guid
    Public Property ProveedorId As System.Guid
    Public Property Fecha As Nullable(Of Date)
    Public Property TransporteId As Nullable(Of System.Guid)
    Public Property Cantidad As Nullable(Of Short)
    Public Property Estado As Nullable(Of Integer)
    Public Property Peso As Nullable(Of Single)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property Transportes As Transportes

End Class
