'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Provincias
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property NombreCorto As String
    Public Property PaisId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property BancosPropios As ICollection(Of BancosPropios) = New HashSet(Of BancosPropios)
    Public Overridable Property Paises As Paises

End Class
