'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Proveedores
    Public Property Id As System.Guid
    Public Property Cuenta As Nullable(Of Integer)
    Public Property Denominacion As String
    Public Property Domicilio As String
    Public Property Telefono As String
    Public Property Celular As String
    Public Property Fax As String
    Public Property Contacto As String
    Public Property Cuit As String
    Public Property TipoDocumento As Nullable(Of Integer)
    Public Property ProvinciaId As Nullable(Of Integer)
    Public Property LocalidadId As Nullable(Of Integer)
    Public Property CondicionCompraId As Nullable(Of Integer)
    Public Property PorcentajeDescuento As Nullable(Of Decimal)
    Public Property Password As String
    Public Property ProveerdorBcoId As Nullable(Of Integer)
    Public Property CBU As String
    Public Property GrupoProveedorId As Nullable(Of Integer)
    Public Property PaginaWeb As String
    Public Property EmailPedido As String
    Public Property Estado As Nullable(Of Integer)
    Public Property Comentarios As String
    Public Property Gto As Nullable(Of Boolean)
    Public Property SucursalAltaId As Integer
    Public Property FechaAlta As Date
    Public Property OperadorAltaId As System.Guid
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

End Class
