'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RegistrosImportaciones
    Public Property Id As System.Guid
    Public Property SucursalImportacion_Id As Nullable(Of Integer)
    Public Property FechaDesde As Nullable(Of Date)
    Public Property FechaHasta As Nullable(Of Date)
    Public Property FechaGeneracion As Nullable(Of Date)
    Public Property Sucursal_Id As Nullable(Of Integer)
    Public Property Operador_id As Nullable(Of System.Guid)
    Public Property PC As String

End Class
