'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RemitosVenta
    Public Property Id As System.Guid
    Public Property LCN As String
    Public Property VentaId As Nullable(Of System.Guid)
    Public Property TipoComprobante As Nullable(Of Integer)
    Public Property ClienteId As Nullable(Of System.Guid)
    Public Property PuntoVenta As Integer
    Public Property NumeroComprobante As String
    Public Property Concepto As String
    Public Property FechaComprobante As Date
    Public Property FechaVencimiento As Nullable(Of Date)
    Public Property FechaEmision As Nullable(Of Date)
    Public Property ImporteNeto As Nullable(Of Decimal)
    Public Property ImporteIVA As Nullable(Of Decimal)
    Public Property Observaciones As String
    Public Property EstadoId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property RemitosVentaDetalle As ICollection(Of RemitosVentaDetalle) = New HashSet(Of RemitosVentaDetalle)

End Class
