'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class REP_VTAS_CTES
    Public Property ClienteSuc As Integer
    Public Property Cliente_Id As Decimal
    Public Property CodTipo As String
    Public Property Desc1 As String
    Public Property Desc2 As String
    Public Property Libro_Id As System.Guid
    Public Property Titulo As String
    Public Property Autor_Id As Decimal
    Public Property vp As Nullable(Of Integer)
    Public Property vc As Nullable(Of Integer)

End Class
