'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class s00CajasSaldo
    Public Property CjLugar As Byte
    Public Property CjOper As String
    Public Property CjSuc As Integer
    Public Property fpEfc As Nullable(Of Single)
    Public Property fpChq As Nullable(Of Single)
    Public Property fpnBono As Nullable(Of Single)
    Public Property nCambio As Nullable(Of Single)
    Public Property SucGr As Nullable(Of Byte)
    Public Property OpeGr As String
    Public Property FeGr As Nullable(Of Date)

End Class
