'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class s00Entidades
    Public Property EntidadTipo As Decimal
    Public Property Entidad_Id As Decimal
    Public Property Cta As String
    Public Property cDescrip As String
    Public Property Domicilio As String
    Public Property Tel1 As String
    Public Property Tel2 As String
    Public Property Tel3 As String
    Public Property Provincia_Id As Nullable(Of Decimal)
    Public Property Localidad_Id As Nullable(Of Decimal)
    Public Property nMutual As Nullable(Of Single)
    Public Property FeGr As Nullable(Of Date)
    Public Property SucGr As Nullable(Of Byte)
    Public Property OpeGr As String

End Class
