'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class s00SueNove
    Public Property kcCodOpe As String
    Public Property nTipo As Byte
    Public Property Concepto As String
    Public Property Cnt As Nullable(Of Byte)
    Public Property Importe As Nullable(Of Single)
    Public Property Tot As Nullable(Of Single)
    Public Property Coment As String
    Public Property Fecha As Nullable(Of Date)
    Public Property RecSuc As Nullable(Of Byte)
    Public Property RecId As String
    Public Property RecLcn As String

End Class
