'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TarjetasMovimientos
    Public Property Id As Integer
    Public Property CajaMovimientoId As System.Guid
    Public Property TarjetaId As Integer
    Public Property BancoId As Nullable(Of Integer)
    Public Property TarjetaLiquidacionId As Nullable(Of System.Guid)
    Public Property LoteCupon As String
    Public Property Fecha As Date
    Public Property Importe As Single
    Public Property Estado As Nullable(Of Byte)
    Public Property NroInt As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property Tarjetas As Tarjetas

End Class
