'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TarjetasLiquidacion
    Public Property Id As System.Guid
    Public Property TarjetaId As Integer
    Public Property CajaId As System.Guid
    Public Property TrjLiq As String
    Public Property Entidad As Nullable(Of Integer)
    Public Property FechaEmision As Nullable(Of Date)
    Public Property Importe As Decimal
    Public Property Imp2 As Nullable(Of Decimal)
    Public Property Imp3 As Nullable(Of Decimal)
    Public Property Imp4 As Nullable(Of Decimal)
    Public Property Imp5 As Nullable(Of Decimal)
    Public Property Imp6 As Nullable(Of Decimal)
    Public Property FechaAlta As Date
    Public Property OperadorAltaId As System.Guid
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property SucursalModificacionId As Nullable(Of Integer)

    Public Overridable Property Cajas As Cajas

End Class
