'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TempComparacionStock
    Public Property Libro_Id As System.Guid
    Public Property CodSuc As Integer
    Public Property StkPr As Nullable(Of Short)
    Public Property StkCn As Nullable(Of Short)
    Public Property StkAud As Nullable(Of Short)
    Public Property FeGr As Nullable(Of Date)
    Public Property FeGrAud As Nullable(Of Date)

End Class
