'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TempLibroIva
    Public Property Iva_Id As Decimal
    Public Property TipoLibro As Nullable(Of Byte)
    Public Property CompSuc As Nullable(Of Byte)
    Public Property CompId As String
    Public Property LCN As String
    Public Property nComp As Nullable(Of Byte)
    Public Property Fecha As Nullable(Of Date)
    Public Property FConta As Nullable(Of Date)
    Public Property Cpto As String
    Public Property Cuit As String
    Public Property INetoGrab As Nullable(Of Single)
    Public Property IExento As Nullable(Of Single)
    Public Property IvaTasa1 As Nullable(Of Single)
    Public Property IvaTasa2 As Nullable(Of Single)
    Public Property IvaTasa3 As Nullable(Of Single)
    Public Property ITotal As Nullable(Of Single)
    Public Property lCerrado As Nullable(Of Byte)

End Class
