'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TitulosConsignacionesVendidas
    Public Property Id As System.Guid
    Public Property nTipo As Nullable(Of Integer)
    Public Property ClienteId As Nullable(Of System.Guid)
    Public Property ProveedorId As Nullable(Of System.Guid)
    Public Property TituloId As Nullable(Of System.Guid)
    Public Property ComprobanteId As Nullable(Of System.Guid)
    Public Property Fecha As Nullable(Of Date)
    Public Property CntCn As Nullable(Of Integer)
    Public Property CntPag As Nullable(Of Single)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property Operadores As Operadores
    Public Overridable Property Sucursales As Sucursales
    Public Overridable Property TiposConsignaciones As TiposConsignaciones
    Public Overridable Property Titulos As Titulos

End Class
