'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TitulosUnicos
    Public Property Id As System.Guid
    Public Property ISBN As String
    Public Property NombreTitulo As String
    Public Property AutorId As Nullable(Of Integer)
    Public Property EditorialId As Nullable(Of Integer)
    Public Property TemaId As Nullable(Of Integer)
    Public Property SubtemaId As Nullable(Of Integer)
    Public Property PrecioVentaTitulo As Nullable(Of Decimal)
    Public Property CodigoBarra As String
    Public Property UnidadesId As Nullable(Of Integer)
    Public Property TomosTitulosId As Nullable(Of Integer)
    Public Property EstadoTituloId As Nullable(Of Integer)
    Public Property nAdicional As Nullable(Of Integer)
    Public Property PesoTitulo As Nullable(Of Integer)
    Public Property PaisId As Nullable(Of Integer)
    Public Property FechaEdicion As Nullable(Of Date)
    Public Property IdiomaId As Nullable(Of Integer)
    Public Property nParte As Nullable(Of Integer)
    Public Property rParte As String
    Public Property Paginas As Nullable(Of Integer)
    Public Property Encuad As Nullable(Of Integer)
    Public Property Comentario As String
    Public Property StkMin As Nullable(Of Integer)
    Public Property FUltVta As Nullable(Of Date)
    Public Property Fingreso As Nullable(Of Date)
    Public Property nControl As Nullable(Of Integer)
    Public Property PresentacionId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

End Class
