'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Titulos
    Public Property Id As System.Guid
    Public Property Cod As String
    Public Property ISBN As String
    Public Property NombreTitulo As String
    Public Property ProveedorId As Nullable(Of System.Guid)
    Public Property AutorId As Nullable(Of Integer)
    Public Property EditorialId As Nullable(Of Integer)
    Public Property TemaId As Nullable(Of Integer)
    Public Property SubtemaId As Nullable(Of Integer)
    Public Property PrecioVentaTitulo As Nullable(Of Decimal)
    Public Property PrecioCompraTitulo As Nullable(Of Decimal)
    Public Property CodigoBarra As String
    Public Property ISBNg As String
    Public Property FechaAltaTitulo As Nullable(Of Date)
    Public Property TipoArticuloId As Nullable(Of Integer)
    Public Property ModoStockId As Nullable(Of Integer)
    Public Property TipoTituloId As Nullable(Of Integer)
    Public Property UnidadesId As Nullable(Of Integer)
    Public Property TomosTitulosId As Nullable(Of Integer)
    Public Property EstadoTituloId As Nullable(Of Integer)
    Public Property AdicionalId As Nullable(Of Integer)
    Public Property PesoTitulo As Nullable(Of Integer)
    Public Property PaisId As Nullable(Of Integer)
    Public Property FechaEdicion As Nullable(Of Date)
    Public Property IdiomaId As Nullable(Of Integer)
    Public Property PartesId As Nullable(Of Integer)
    Public Property Paginas As Nullable(Of Integer)
    Public Property Encuad As Nullable(Of Integer)
    Public Property Comentario As String
    Public Property StkMin As Nullable(Of Integer)
    Public Property FUltVta As Nullable(Of Date)
    Public Property Fingreso As Nullable(Of Date)
    Public Property nControl As Nullable(Of Integer)
    Public Property UbicacionId As Nullable(Of Integer)
    Public Property TituloUnicoId As Nullable(Of System.Guid)
    Public Property PresentacionId As Nullable(Of Integer)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property ClientesMontosFavorDetalle As ICollection(Of ClientesMontosFavorDetalle) = New HashSet(Of ClientesMontosFavorDetalle)
    Public Overridable Property NotasDeVentaDetalle As ICollection(Of NotasDeVentaDetalle) = New HashSet(Of NotasDeVentaDetalle)
    Public Overridable Property RemitosCompraDetalle As ICollection(Of RemitosCompraDetalle) = New HashSet(Of RemitosCompraDetalle)
    Public Overridable Property RemitosVentaDetalle As ICollection(Of RemitosVentaDetalle) = New HashSet(Of RemitosVentaDetalle)
    Public Overridable Property TitulosConsignacionesVendidas As ICollection(Of TitulosConsignacionesVendidas) = New HashSet(Of TitulosConsignacionesVendidas)

End Class
