'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TitulosUbicacion
    Public Property Id As Integer
    Public Property Piso As Nullable(Of Integer)
    Public Property AreaId As Nullable(Of Integer)
    Public Property TemaId As Nullable(Of Integer)
    Public Property EspecialidadId As Nullable(Of Integer)
    Public Property SubEspecialidadId As Nullable(Of Integer)
    Public Property Path As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

    Public Overridable Property Areas As Areas
    Public Overridable Property Especialidades As Especialidades

End Class
