'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Transferencias
    Public Property Id As System.Guid
    Public Property SucursalId As Integer
    Public Property Numero As Integer
    Public Property LCN As String
    Public Property CodSucDest As Nullable(Of Byte)
    Public Property Fecha As Nullable(Of Date)
    Public Property Concepto As String
    Public Property Obs As String
    Public Property FAnula As Nullable(Of Date)
    Public Property FRecibe As Nullable(Of Date)
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

End Class
