'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VentasPendientesEntrega
    Public Property Id As Integer
    Public Property FacturaId As Nullable(Of System.Guid)
    Public Property TituloId As Nullable(Of System.Guid)
    Public Property CantidadPropia As Nullable(Of Integer)
    Public Property CantidadConsig As Nullable(Of Integer)
    Public Property Precio As Nullable(Of Decimal)
    Public Property CantidadAuditada As Nullable(Of Integer)
    Public Property FechaEntrega As Nullable(Of Date)
    Public Property OeradorEntrega As Nullable(Of System.Guid)
    Public Property PcEntrega As String
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)

End Class
