'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ventas
    Public Property Id As System.Guid
    Public Property LCN As String
    Public Property ComprobanteId As Integer
    Public Property ClienteId As System.Guid
    Public Property LetraComprobante As String
    Public Property PuntoVenta As Integer
    Public Property NumeroComprobante As Integer
    Public Property FechaComprobante As Nullable(Of Date)
    Public Property FechaVencimiento As Nullable(Of Date)
    Public Property CondicionVentaId As Nullable(Of Integer)
    Public Property Concepto As String
    Public Property ImporteNeto As Decimal
    Public Property ImporteIva As Decimal
    Public Property ImporteSena As Nullable(Of Decimal)
    Public Property FechaUltimoPago As Nullable(Of Date)
    Public Property TotalPagado As Nullable(Of Decimal)
    Public Property EstadoVentaId As Integer
    Public Property FechaAlta As Nullable(Of Date)
    Public Property SucursalAltaId As Nullable(Of Integer)
    Public Property OperadorAltaId As Nullable(Of System.Guid)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property SucursalModificacionId As Nullable(Of Integer)
    Public Property OperadorModificacionId As Nullable(Of System.Guid)
    Public Property OperadorAutoriza As Nullable(Of System.Guid)
    Public Property ValidacionUsuario As String

    Public Overridable Property NotasDeVenta As ICollection(Of NotasDeVenta) = New HashSet(Of NotasDeVenta)

End Class
